package com.animame.editor

import android.graphics.*
import kotlin.math.*
import kotlin.random.Random

object AdvancedBrushRenderer {
    fun draw(c: Canvas, stroke: StrokeData, tint: Int? = null) {
        val pts = stroke.samples
        if (pts.isEmpty()) return
        val s = stroke.brushSettings.copy(size = stroke.size, opacity = stroke.opacity).normalized()
        val color = tint ?: stroke.color
        val seed = stroke.id.hashCode().toLong()
        when (family(stroke.brushId, s.brushType)) {
            "eraser" -> renderEraser(c, pts, s)
            "air" -> renderAir(c, pts, color, s)
            "water" -> renderWater(c, pts, color, s, seed)
            "paint" -> renderPaint(c, pts, color, s, seed)
            "pencil" -> renderPencil(c, pts, color, s, seed)
            "ink" -> renderInk(c, pts, color, s)
            "marker" -> renderMarker(c, pts, color, s)
            "chalk" -> renderChalk(c, pts, color, s, seed)
            "smudge" -> renderSmudge(c, pts, color, s)
            "particle" -> renderParticles(c, pts, color, s, seed)
            "nature" -> renderNature(c, pts, color, s, seed, stroke.brushId)
            "effect" -> renderEffect(c, pts, color, s, seed, stroke.brushId)
            "texture" -> renderTexture(c, pts, color, s, seed)
            else -> renderBasic(c, pts, color, s)
        }
    }
    private fun family(id:String,type:String):String { val x=(id+" "+type).lowercase(); return when {
        x.contains("eraser")->"eraser"; x.contains("water")||x.contains("gouache")||x.contains("wash")->"water"; x.contains("oil")||x.contains("acrylic")||x.contains("impasto")||x.contains("paint")->"paint"; x.contains("pencil")||x.contains("graphite")||x.contains("sketch")||x.contains("crayon")->"pencil"; x.contains("ink")||x.contains("pen")||x.contains("fountain")->"ink"; x.contains("marker")||x.contains("felt")||x.contains("highlighter")->"marker"; x.contains("chalk")||x.contains("pastel")||x.contains("charcoal")->"chalk"; x.contains("airbrush")||x.contains("air")->"air"; x.contains("smudge")||x.contains("blend")||x.contains("mix")->"smudge"; x.contains("spray")||x.contains("particle")||x.contains("stamp")||x.contains("speckle")->"particle"; x.contains("grass")||x.contains("leaf")||x.contains("leaves")||x.contains("fur")||x.contains("hair")||x.contains("cloud")||x.contains("vine")||x.contains("flower")||x.contains("branch")||x.contains("bamboo")->"nature"; x.contains("fire")||x.contains("light")||x.contains("glow")||x.contains("neon")||x.contains("star")||x.contains("spark")||x.contains("glitter")||x.contains("bloom")->"effect"; x.contains("texture")||x.contains("canvas")||x.contains("paper")||x.contains("noise")->"texture"; else->"basic" } }
    private fun paint(color:Int,a:Int,aa:Boolean,mode:PorterDuff.Mode?=null)=Paint().apply{isAntiAlias=aa;this.color=color;this.alpha=a.coerceIn(0,255);style=Paint.Style.STROKE;strokeCap=Paint.Cap.ROUND;strokeJoin=Paint.Join.ROUND;if(mode!=null)xfermode=PorterDuffXfermode(mode)}
    private fun renderBasic(c:Canvas,p:List<StrokeSample>,color:Int,s:BrushSettings){if(p.size==1){dab(c,p[0].x,p[0].y,color,s,p[0].pressure);return};val q=paint(color,255,s.antialias);var d0=0f;val total=length(p);for(i in 1 until p.size){val a=p[i-1];val b=p[i];val d=hypot(b.x-a.x,b.y-a.y);val pr=((a.pressure+b.pressure)*.5f).coerceIn(.05f,1.5f);q.strokeWidth=s.radiusFor(pr,(a.tilt+b.tilt)*.5f,speed(a,b));q.alpha=alpha(s.opacityFor(pr,(a.tilt+b.tilt)*.5f,d0,total,speed(a,b)));c.drawLine(a.x,a.y,b.x,b.y,q);d0+=d};if(s.spacing>.2f||s.jitter>0f||s.scatter)dabs(c,p,color,s)}
    private fun renderInk(c:Canvas,p:List<StrokeSample>,color:Int,s:BrushSettings){val q=paint(color,255,s.antialias);val total=length(p);var d0=0f;for(i in 1 until p.size){val a=p[i-1];val b=p[i];val d=hypot(b.x-a.x,b.y-a.y);val pr=(a.pressure+b.pressure)*.5f;q.strokeWidth=s.radiusFor(pr,(a.tilt+b.tilt)*.5f,speed(a,b));q.alpha=alpha(s.opacityFor(pr,0f,d0,total,speed(a,b)));c.drawLine(a.x,a.y,b.x,b.y,q);d0+=d}}
    private fun renderPencil(c:Canvas,p:List<StrokeSample>,color:Int,s:BrushSettings,seed:Long){val q=paint(color,alpha(s.opacity*.72f),s.antialias);q.strokeWidth=max(1f,s.size*.55f);path(c,p,q);val r=Random(seed);repeat(3){val z=paint(color,alpha(s.opacity*.22f),false);z.strokeWidth=max(.5f,s.size*.08f);val off=s.size*.22f;path(c,p.map{StrokeSample(it.x+(r.nextFloat()-.5f)*off,it.y+(r.nextFloat()-.5f)*off,it.pressure,it.timeMs,it.tilt,it.orientation)},z)}}
    private fun renderMarker(c:Canvas,p:List<StrokeSample>,color:Int,s:BrushSettings){val q=paint(color,alpha(s.opacity),s.antialias);q.strokeWidth=s.size;q.strokeCap=Paint.Cap.SQUARE;path(c,p,q);if(s.feather>.2f){q.alpha=alpha(s.opacity*.12f);q.strokeWidth=s.size*1.12f;path(c,p,q)}}
    private fun renderPaint(c:Canvas,p:List<StrokeSample>,color:Int,s:BrushSettings,seed:Long){val r=Random(seed);val u=paint(color,alpha(s.opacity*.42f),s.antialias);u.strokeWidth=s.size*1.18f;path(c,p,u);val b=paint(color,alpha(s.opacity*.72f),s.antialias);b.strokeWidth=s.size*.88f;path(c,p,b);val h=paint(lighten(color,.18f),alpha(s.opacity*.16f),s.antialias);h.strokeWidth=max(1f,s.size*.12f);path(c,p,p.map{StrokeSample(it.x+(r.nextFloat()-.5f)*s.size*.15f,it.y+(r.nextFloat()-.5f)*s.size*.15f,it.pressure,it.timeMs,it.tilt,it.orientation)},h);dabs(c,p,color,s.copy(spacing=max(.08f,s.spacing),jitter=max(.04f,s.jitter)),seed)}
    private fun renderWater(c:Canvas,p:List<StrokeSample>,color:Int,s:BrushSettings,seed:Long){val q=paint(color,alpha(s.opacity*.25f),s.antialias);q.strokeWidth=s.size*1.35f;q.maskFilter=BlurMaskFilter(s.size*(.2f+.65f*s.feather),BlurMaskFilter.Blur.NORMAL);path(c,p,q);val b=paint(color,alpha(s.opacity*.32f),s.antialias);b.strokeWidth=s.size*.72f;path(c,p,b);dabs(c,p,color,s.copy(opacity=s.opacity*.35f,spacing=max(.08f,s.spacing)),seed);if(s.textureStrength>.05f)textureDabs(c,p,color,s,seed)}
    private fun renderAir(c:Canvas,p:List<StrokeSample>,color:Int,s:BrushSettings){val total=length(p);var d0=0f;for(i in p.indices){if(i>0)d0+=dist(p[i-1],p[i]);val q=p[i];val radius=s.radiusFor(q.pressure,q.tilt);val z=Paint().apply{isAntiAlias=s.antialias;this.color=color;style=Paint.Style.FILL;this.alpha=alpha(s.opacityFor(q.pressure,q.tilt,d0,total))};z.shader=RadialGradient(q.x,q.y,radius,intArrayOf(Color.argb(z.alpha,Color.red(color),Color.green(color),Color.blue(color)),Color.argb(0,Color.red(color),Color.green(color),Color.blue(color))),floatArrayOf(0f,1f),Shader.TileMode.CLAMP);c.drawCircle(q.x,q.y,radius,z)}}
    private fun renderChalk(c:Canvas,p:List<StrokeSample>,color:Int,s:BrushSettings,seed:Long){val q=paint(color,alpha(s.opacity*.7f),false);q.strokeWidth=s.size*.7f;path(c,p,q);textureDabs(c,p,color,s.copy(opacity=s.opacity*.35f,textureStrength=max(.45f,s.textureStrength)),seed)}
    private fun renderSmudge(c:Canvas,p:List<StrokeSample>,color:Int,s:BrushSettings){val q=paint(color,alpha(s.opacity*.22f),s.antialias);q.strokeWidth=s.size*1.15f;path(c,p,q);val z=paint(lighten(color,.08f),alpha(s.opacity*.12f),s.antialias);z.strokeWidth=s.size*.72f;path(c,p,z)}
    private fun renderParticles(c:Canvas,p:List<StrokeSample>,color:Int,s:BrushSettings,seed:Long){val r=Random(seed);val density=max(1,(s.particleDensity*8f+s.size/10f).roundToInt());for(q in p)repeat(density){val rr=s.particleSize.coerceAtLeast(s.size*.18f)*(.45f+r.nextFloat());val j=s.size*(s.jitterPosition+.15f);val x=q.x+(r.nextFloat()-.5f)*j;val y=q.y+(r.nextFloat()-.5f)*j;val z=Paint().apply{isAntiAlias=s.antialias;style=Paint.Style.FILL;this.color=color;this.alpha=alpha(s.opacity*.45f)};c.drawCircle(x,y,rr*.5f,z)}}
    private fun renderNature(c:Canvas,p:List<StrokeSample>,color:Int,s:BrushSettings,seed:Long,id:String){val r=Random(seed);for(i in 0 until p.size step 2){val q=p[i];repeat(3+(s.particleDensity*5).roundToInt()){val x=q.x+(r.nextFloat()-.5f)*s.size;val y=q.y+(r.nextFloat()-.5f)*s.size;val z=Paint().apply{isAntiAlias=true;style=Paint.Style.FILL;this.color=color;this.alpha=alpha(s.opacity*.7f)};when{ id.contains("grass")||id.contains("bamboo")-> {z.style=Paint.Style.STROKE;z.strokeWidth=max(1f,s.size*.08f);c.drawLine(x,y,x+(r.nextFloat()-.5f)*s.size*.6f,y-s.size*(.5f+r.nextFloat()*1.5f),z)};id.contains("fur")||id.contains("hair")-> {z.style=Paint.Style.STROKE;z.strokeWidth=max(1f,s.size*.07f);c.drawLine(x,y,x+(r.nextFloat()-.5f)*s.size,y-s.size*(.2f+r.nextFloat()),z)};else->{c.save();c.rotate(r.nextFloat()*180f,q.x,q.y);c.drawOval(x-s.size*.3f,y-s.size*.16f,x+s.size*.3f,y+s.size*.16f,z);c.restore()}}}}}
    private fun renderEffect(c:Canvas,p:List<StrokeSample>,color:Int,s:BrushSettings,seed:Long,id:String){val q=paint(color,alpha(s.opacity*.18f),s.antialias);q.strokeWidth=s.size*1.8f;q.maskFilter=BlurMaskFilter(s.size*.9f,BlurMaskFilter.Blur.NORMAL);path(c,p,q);val core=paint(if(id.contains("fire"))Color.rgb(255,150,35) else Color.WHITE,alpha(s.opacity*.9f),s.antialias);core.strokeWidth=max(1f,s.size*.25f);path(c,p,core);if(id.contains("star")||id.contains("spark")||id.contains("glitter")){val r=Random(seed);repeat(max(2,p.size/3)){val q0=p[r.nextInt(p.size)];val z=Paint().apply{isAntiAlias=true;style=Paint.Style.FILL;this.color=Color.WHITE;this.alpha=alpha(s.opacity)};c.drawCircle(q0.x+(r.nextFloat()-.5f)*s.size*2f,q0.y+(r.nextFloat()-.5f)*s.size*2f,max(1f,s.size*.12f),z)}}}
    private fun renderTexture(c:Canvas,p:List<StrokeSample>,color:Int,s:BrushSettings,seed:Long){renderBasic(c,p,color,s.copy(opacity=s.opacity*.7f));textureDabs(c,p,color,s.copy(opacity=s.opacity*.45f,textureStrength=max(.4f,s.textureStrength)),seed)}
    private fun renderEraser(c:Canvas,p:List<StrokeSample>,s:BrushSettings){val q=paint(Color.TRANSPARENT,255,s.antialias,PorterDuff.Mode.DST_OUT);q.strokeWidth=s.size;path(c,p,q);q.xfermode=null}
    private fun dabs(c:Canvas,p:List<StrokeSample>,color:Int,s:BrushSettings,seed:Long=0L){val r=Random(seed);val step=max(1f,s.size*s.spacing);var carry=0f;for(i in 1 until p.size){val a=p[i-1];val b=p[i];val d=dist(a,b);var t=(step-carry).coerceAtLeast(0f);while(t<=d){val u=if(d==0f)0f else t/d;val x=a.x+(b.x-a.x)*u;val y=a.y+(b.y-a.y)*u;val j=s.size*s.jitterPosition;dab(c,x+(r.nextFloat()-.5f)*j,y+(r.nextFloat()-.5f)*j,color,s,(a.pressure+b.pressure)*.5f);t+=step};carry=(carry+d)%step}}
    private fun textureDabs(c:Canvas,p:List<StrokeSample>,color:Int,s:BrushSettings,seed:Long){val r=Random(seed+31);val count=max(2,(s.size*s.textureStrength/2f).roundToInt());for(i in 0 until p.size step 2)repeat(count){val j=s.size*(.25f+.75f*s.textureStrength);val z=Paint().apply{isAntiAlias=false;style=Paint.Style.FILL;this.color=color;this.alpha=alpha(s.opacity*.12f)};val q=p[i];c.drawCircle(q.x+(r.nextFloat()-.5f)*j,q.y+(r.nextFloat()-.5f)*j,max(.4f,s.size*.015f),z)}}
    private fun dab(c:Canvas,x:Float,y:Float,color:Int,s:BrushSettings,pressure:Float){val q=Paint().apply{isAntiAlias=s.antialias;style=Paint.Style.FILL;this.color=color;this.alpha=alpha(s.opacityFor(pressure,0f,0f,0f))};val rx=s.radiusFor(pressure,0f)/2f;val ry=rx*s.aspect.coerceIn(.05f,4f);c.drawOval(x-rx,y-ry,x+rx,y+ry,q)}
    private fun path(c:Canvas,p:List<StrokeSample>,q:Paint){if(p.isEmpty())return;val x=Path();x.moveTo(p[0].x,p[0].y);for(i in 1 until p.size){val a=p[i-1];val b=p[i];x.quadTo(a.x,a.y,(a.x+b.x)/2f,(a.y+b.y)/2f)};if(p.size>1)x.lineTo(p.last().x,p.last().y);c.drawPath(x,q)}
    private fun length(p:List<StrokeSample>):Float{var n=0f;for(i in 1 until p.size)n+=dist(p[i-1],p[i]);return n}
    private fun dist(a:StrokeSample,b:StrokeSample)=hypot(b.x-a.x,b.y-a.y)
    private fun speed(a:StrokeSample,b:StrokeSample):Float{val dt=max(1L,b.timeMs-a.timeMs);return (dist(a,b)/dt*.08f).coerceIn(0f,1f)}
    private fun alpha(v:Float)=(v*255f).roundToInt().coerceIn(0,255)
    private fun lighten(c:Int,a:Float)=Color.rgb((Color.red(c)+(255-Color.red(c))*a).roundToInt(),(Color.green(c)+(255-Color.green(c))*a).roundToInt(),(Color.blue(c)+(255-Color.blue(c))*a).roundToInt())
}