package com.animame.editor

import android.app.Activity
import android.content.Context
import android.graphics.*
import android.net.Uri
import android.view.MotionEvent
import android.view.View
import kotlin.math.*

open class AnimationEditorViewV5(context:Context):View(context){
    private enum class Mode{HOME,EDITOR};private enum class Panel{OPTIONS,BRUSHES,LAYERS,TIMELINE,CAMERA,RULERS};private enum class Tool{BRUSH,PENCIL,ERASER,LASSO,FILL,PAN,TRANSFORM,LINE,RECTANGLE,ELLIPSE}
    private var mode=Mode.HOME;private var panel:Panel?=Panel.OPTIONS;private var dialog=false;private var menu=false;private var tool=Tool.BRUSH
    private var project:AnimationProject?=null;private var document=AnimationDocument();private var projectName="Untitled";private var fps=24;private var cw=1280;private var ch=720;private var margin=0;private var selectedLayerId=document.activeLayer.id
    private var selectedBrush=BrushCatalog.presets.first();private var brushSettings=selectedBrush.defaults.copy();private var brushSize=brushSettings.size;private var opacity=brushSettings.opacity;private var stabilizer=20f;private var realTimeStabilizer=true;private var antiAlias=true;private var ruler=0;private var symmetry=6
    private var selectedColor=Color.BLACK;private var previousColor=Color.BLACK;private var colorPopup=false;private var colorPaletteMode=false
    private val palette=mutableListOf(Color.BLACK,Color.WHITE,Color.RED,Color.GREEN,Color.BLUE,Color.YELLOW,Color.CYAN,Color.MAGENTA,Color.rgb(255,128,0),Color.rgb(128,64,32),Color.rgb(255,180,180),Color.rgb(80,80,80));private val colorHistory=ArrayDeque<Int>()
    private var playing=false;private var lastPlayTime=0L;private var frameAccumulator=0f;private val viewport=CanvasViewport();private val settings get()=EditorSettingsStore.current;private val history=EditorHistory(120);private val lowLatency=LowLatencyStabilizer()
    private var cameraX=0f;private var cameraY=0f;private var cameraScale=1f;private var cameraRotation=0f;private val samples=mutableListOf<Stabilizer.Sample>();private var current:Path?=null;private var lastPoint:PointF?=null;private var lastTime=0L;private val lasso=mutableListOf<PointF>();private val selectedStrokeIds=mutableSetOf<String>();private var gestureStart:PointF?=null;private val ui=Paint(Paint.ANTI_ALIAS_FLAG);private val bitmapCache=HashMap<String,Bitmap>()
    private var exportFormat:AnimationExportEngine.Format?=null
    init{setLayerType(View.LAYER_TYPE_SOFTWARE,null)}
    override fun onDraw(c:Canvas){if(mode==Mode.HOME)drawHome(c)else drawEditor(c);if(dialog)drawDialog(c);if(menu)drawMenu(c);if(colorPopup)drawColorPopup(c);if(playing){val now=System.currentTimeMillis();if(lastPlayTime==0L)lastPlayTime=now;frameAccumulator+=(now-lastPlayTime)/1000f*document.fps;lastPlayTime=now;while(frameAccumulator>=1f){document.currentFrame++;frameAccumulator-=1f;if(document.currentFrame>document.playbackEnd)document.currentFrame=document.playbackStart};postInvalidateDelayed(16)}}
    private fun bg(c:Canvas){ui.style=Paint.Style.FILL;ui.color=Color.rgb(16,17,19);c.drawRect(0f,0f,width.toFloat(),height.toFloat(),ui)}
    private fun drawHome(c:Canvas){bg(c);ui.color=Color.rgb(27,29,32);c.drawRect(0f,0f,width.toFloat(),54f,ui);text(c,"ANIMA-ME",22f,35f,Color.WHITE,18f);text(c,"Sort by date",width-115f,35f,Color.LTGRAY,10f);if(ProjectStore.projects.isEmpty())text(c,"No projects",width/2f-35f,height/2f,Color.LTGRAY,14f)else{var y=80f;ProjectStore.projects.forEach{p->ui.color=Color.rgb(36,39,43);c.drawRoundRect(24f,y,300f,y+150f,8f,8f,ui);text(c,p.name,40f,y+122f,Color.WHITE,12f);text(c,"${p.fps} fps   ${p.cameraWidth} x ${p.cameraHeight}",40f,y+141f,Color.GRAY,9f);y+=170f}};ui.color=Color.rgb(52,55,60);c.drawRoundRect(width-190f,height-76f,width-24f,height-26f,10f,10f,ui);text(c,"New project",width-154f,height-45f,Color.WHITE,12f)}
    private fun drawEditor(c:Canvas){bg(c);val w=width.toFloat();val h=height.toFloat();ui.color=Color.rgb(27,29,32);c.drawRect(0f,0f,w,50f,ui);text(c,"☰",18f,34f,Color.WHITE,24f);text(c,"ANIMA-ME",52f,32f,Color.WHITE,15f);text(c,project?.name?:"Untitled",150f,32f,Color.LTGRAY,12f);text(c,"${document.fps} FPS",w-72f,32f,Color.LTGRAY,10f);ui.color=selectedColor;c.drawRoundRect(w-170f,12f,w-136f,38f,5f,5f,ui);ui.style=Paint.Style.STROKE;ui.color=Color.WHITE;ui.strokeWidth=1f;c.drawRoundRect(w-170f,12f,w-136f,38f,5f,5f,ui);ui.style=Paint.Style.FILL
        timelineTop(c);val r=canvasRect();ui.color=Color.WHITE;c.drawRect(r);c.save();c.clipRect(r);c.concat(editorMatrix(r));drawOnion(c);drawCurrentFrame(c);if(current!=null)drawPreviewStroke(c);c.restore();drawRuler(c,r);drawLasso(c);leftPanels(c);rail(c);if(panel!=null)drawPanel(c,w-300f,h)}
    private fun timelineTop(c:Canvas){val h=100f;ui.color=Color.rgb(35,37,40);c.drawRect(0f,50f,width.toFloat(),50f+h,ui);text(c,"Drawing duration: ${max(1,document.duration)} frames",72f,70f,Color.WHITE,10f);text(c,"Start: ${document.playbackStart+1}",470f,70f,Color.LTGRAY,9f);text(c,"End: ${document.playbackEnd+1}",570f,70f,Color.LTGRAY,9f);text(c,"Delete drawing",width-360f,70f,Color.LTGRAY,9f);text(c,"Label drawing",width-270f,70f,Color.LTGRAY,9f);text(c,"Make cycle",width-180f,70f,Color.LTGRAY,9f);text(c,"Edit multiple",width-100f,70f,Color.LTGRAY,9f);val start=190f;val cell=30f;for(i in 0 until min(document.duration,38)){val x=start+i*cell;ui.color=if(i==document.currentFrame)Color.rgb(235,235,235)else Color.rgb(76,79,84);c.drawRect(x,84f,x+cell-2f,108f,ui);text(c,"${i+1}",x+8f,101f,if(i==document.currentFrame)Color.DKGRAY else Color.LTGRAY,7f)};text(c,"Layer 1",105f,123f,Color.LTGRAY,9f);ui.color=Color.rgb(73,76,81);c.drawRoundRect(190f,112f,width-300f,142f,5f,5f,ui);text(c,"Frame ${document.currentFrame+1}/${document.duration}",205f,131f,Color.LTGRAY,8f);ui.color=Color.rgb(235,235,235);val px=190f+document.currentFrame*cell;c.drawRect(px,50f,px+3f,150f,ui)}
    private fun drawCurrentFrame(c:Canvas){document.layers.asReversed().filter{it.visible}.forEach{layer->layer.frameAt(document.currentFrame)?.let{f->drawRaster(c,f);f.strokes.forEach{s->drawStroke(c,s)}}}}
    private fun drawRaster(c:Canvas,f:DrawingFrame){val path=f.rasterPath?:return;val b=bitmapCache.getOrPut(path){BitmapFactory.decodeFile(path)?:return};c.drawBitmap(b,null,RectF(0f,0f,document.width.toFloat(),document.height.toFloat()),null)}
    private fun drawOnion(c:Canvas){if(!document.onion.enabled)return;val layer=document.layers.firstOrNull{it.id==selectedLayerId}?:return;val a=(document.onion.opacity*2.55f).roundToInt().coerceIn(0,255);layer.previousFrames(document.currentFrame,document.onion.previousCount).forEach{(_,f)->f.strokes.forEach{s->drawStroke(c,s,if(document.onion.tintPrevious)Color.argb(a,80,150,255)else null)}};layer.nextFrames(document.currentFrame,document.onion.nextCount).forEach{(_,f)->f.strokes.forEach{s->drawStroke(c,s,if(document.onion.tintNext)Color.argb(a,255,110,110)else null)}}}
    private fun drawStroke(c:Canvas,s:StrokeData,tint:Int?=null){if(s.samples.isEmpty())return;val bs=s.brushSettings.copy(size=s.size,opacity=s.opacity).normalized();val list=s.samples;val total=strokeLength(list);val p=Paint(Paint.ANTI_ALIAS_FLAG).apply{style=Paint.Style.STROKE;strokeCap=Paint.Cap.ROUND;strokeJoin=Paint.Join.ROUND;isAntiAlias=bs.antialias&&antiAlias;color=tint?:s.color};if(bs.eraser&&! (tint!=null))p.xfermode=PorterDuffXfermode(PorterDuff.Mode.DST_OUT);if(list.size==1){p.style=Paint.Style.FILL;p.alpha=(bs.opacityFor(list[0].pressure,list[0].tilt,0f,total)*255).roundToInt().coerceIn(0,255);c.drawCircle(list[0].x,list[0].y,bs.radiusFor(list[0].pressure,list[0].tilt)/2,p);return};var dist=0f;for(i in 1 until list.size){val a=list[i-1];val b=list[i];val d=hypot(b.x-a.x,b.y-a.y);val pr=((a.pressure+b.pressure)/2).coerceIn(.05f,1.5f);val width=bs.radiusFor(pr,(a.tilt+b.tilt)/2);p.strokeWidth=width;p.alpha=(bs.opacityFor(pr,(a.tilt+b.tilt)/2,dist,total)*255).roundToInt().coerceIn(0,255);c.drawLine(a.x,a.y,b.x,b.y,p);dist+=d};p.xfermode=null;if(selectedStrokeIds.contains(s.id)&&tint==null){val q=Paint(Paint.ANTI_ALIAS_FLAG).apply{style=Paint.Style.STROKE;color=Color.CYAN;strokeWidth=2f;pathEffect=DashPathEffect(floatArrayOf(5f,5f),0f)};val path=Path().apply{moveTo(list[0].x,list[0].y);list.drop(1).forEach{lineTo(it.x,it.y)}};c.drawPath(path,q)}}
    private fun drawPreviewStroke(c:Canvas){if(samples.isEmpty())return;drawStroke(c,StrokeData(brushId=selectedBrush.id,color=selectedColor,size=brushSize,opacity=opacity,brushSettings=brushSettings.copy(size=brushSize,opacity=opacity,eraser=tool==Tool.ERASER),samples=samples.map{StrokeSample(it.point.x,it.point.y,it.pressure,it.timeMs,it.tilt)}.toMutableList()))}
    private fun drawLasso(c:Canvas){if(lasso.size<2)return;val p=Paint(Paint.ANTI_ALIAS_FLAG).apply{style=Paint.Style.STROKE;color=Color.YELLOW;strokeWidth=2f;pathEffect=DashPathEffect(floatArrayOf(8f,6f),0f)};val q=Path().apply{moveTo(lasso[0].x,lasso[0].y);lasso.drop(1).forEach{lineTo(it.x,it.y)};if(tool!=Tool.LASSO)close()};c.drawPath(q,p)}
    private fun leftPanels(c:Canvas){val names=listOf("Timeline","Tool options","Brushes","Layers","Camera","Rulers");var y=160f;names.forEachIndexed{i,n->{val active=panel==Panel.values()[i];ui.color=if(active)Color.rgb(245,241,220)else Color.rgb(65,68,72);c.drawRoundRect(70f,y,180f,y+48f,5f,5f,ui);text(c,n,82f,y+29f,if(active)Color.rgb(60,60,60)else Color.LTGRAY,9f);y+=53f}}}
    private fun rail(c:Canvas){ui.color=Color.rgb(31,33,36);c.drawRect(0f,155f,62f,height.toFloat(),ui);val names=listOf("BR","PE","ER","LA","FI","PI","MV","TR","LN","RE","EL");names.forEachIndexed{i,n->{if(Tool.values().getOrNull(i)==tool){ui.color=Color.rgb(70,75,84);c.drawRoundRect(4f,160f+i*41f,58f,195f+i*41f,6f,6f,ui)};text(c,n,19f,181f+i*41f,Color.WHITE,9f)}}}
    private fun drawPanel(c:Canvas,x:Float,h:Float){ui.color=Color.rgb(29,31,34);c.drawRect(x,150f,width.toFloat(),h,ui);text(c,when(panel){Panel.OPTIONS->"TOOL OPTIONS";Panel.BRUSHES->"BRUSH LIBRARY";Panel.LAYERS->"LAYERS";Panel.TIMELINE->"TIMELINE";Panel.CAMERA->"CAMERA / TRANSFORM";Panel.RULERS->"RULERS";null->""},x+14f,178f,Color.WHITE,13f);when(panel){Panel.OPTIONS->options(c,x+14f);Panel.BRUSHES->brushes(c,x+14f);Panel.LAYERS->layers(c,x+14f);Panel.TIMELINE->timelinePanel(c,x+14f);Panel.CAMERA->camera(c,x+14f);Panel.RULERS->rulers(c,x+14f);null->Unit}}
    private fun options(c:Canvas,x:Float){text(c,"COLOR",x,206f,Color.WHITE,11f);ui.color=selectedColor;c.drawRect(x+170f,192f,x+215f,216f,ui);text(c,"TOOL  ${tool.name}",x,232f,Color.WHITE,12f);text(c,"BRUSH  ${selectedBrush.name}",x,252f,Color.WHITE,11f);text(c,"SIZE  ${brushSize.roundToInt()} px",x,274f,Color.LTGRAY,10f);text(c,"OPACITY  ${(opacity*100).roundToInt()}%",x,296f,Color.LTGRAY,10f);text(c,"HARDNESS  ${(brushSettings.hardness*100).roundToInt()}%",x,318f,Color.LTGRAY,10f);text(c,"FEATHER  ${(brushSettings.feather*100).roundToInt()}%",x,338f,Color.LTGRAY,10f);text(c,"FLOW  ${(brushSettings.flow*100).roundToInt()}%",x,358f,Color.LTGRAY,10f);text(c,"SPACING  ${(brushSettings.spacing*100).roundToInt()}%",x,378f,Color.LTGRAY,10f);text(c,"SMOOTH  ${if(isSmoothEnabled())"ON" else "OFF"}",x,400f,Color.LTGRAY,10f);text(c,"STABILIZER  ${stabilizer.roundToInt()}%  ${if(realTimeStabilizer)"REAL TIME" else "AFTER"}",x,420f,Color.LTGRAY,10f);text(c,"ANTI-ALIAS  ${if(antiAlias)"ON" else "OFF"}",x,440f,Color.LTGRAY,10f)}
    private fun brushes(c:Canvas,x:Float){var y=206f;BrushCatalog.families.forEach{f->if(y<height-20){text(c,f,x,y,Color.WHITE,10f);y+=18f;BrushCatalog.presets.filter{it.family==f}.forEach{p->if(y<height-20){text(c,if(p.id==selectedBrush.id)"• ${p.name}" else "  ${p.name}",x+6f,y,if(p.id==selectedBrush.id)Color.WHITE else Color.GRAY,9f);y+=16f}};y+=4f}}}
    private fun layers(c:Canvas,x:Float){text(c,"+ NEW LAYER",x,206f,Color.WHITE,10f);var y=236f;document.layers.forEach{l->text(c,if(l.id==selectedLayerId)"• ${l.name}" else "  ${l.name}",x,y,Color.LTGRAY,10f);text(c,"${if(l.visible)"VISIBLE" else "HIDDEN"}  ${if(l.locked)"LOCKED" else "UNLOCKED"}",x+115f,y,Color.GRAY,8f);y+=30f}}
    private fun timelinePanel(c:Canvas,x:Float){text(c,"CURRENT FRAME  ${document.currentFrame+1} / ${document.duration}",x,206f,Color.WHITE,10f);text(c,"ONION SKIN   ${if(document.onion.enabled)"ON" else "OFF"}",x,236f,Color.LTGRAY,10f);text(c,"PREVIOUS ${document.onion.previousCount}   NEXT ${document.onion.nextCount}",x,264f,Color.LTGRAY,10f);text(c,"OPACITY ${document.onion.opacity}%",x,292f,Color.LTGRAY,10f)}
    private fun camera(c:Canvas,x:Float){text(c,"POSITION  ${cameraX.roundToInt()}, ${cameraY.roundToInt()}",x,206f,Color.LTGRAY,10f);text(c,"SCALE  ${(cameraScale*100).roundToInt()}%",x,236f,Color.LTGRAY,10f);text(c,"ROTATION  ${cameraRotation.roundToInt()}°",x,266f,Color.LTGRAY,10f);text(c,"RESET CAMERA",x,316f,Color.WHITE,10f)}
    private fun rulers(c:Canvas,x:Float){listOf("STRAIGHT RULER","CIRCULAR RULER","ELLIPSE RULER","RADIAL RULER","MIRROR RULER","KALEIDOSCOPE RULER","ROTATION RULER","ARRAY RULER","PERSPECTIVE ARRAY RULER").forEachIndexed{i,s->text(c,if(ruler==i+1)"• $s" else "  $s",x,206f+i*24f,if(ruler==i+1)Color.WHITE else Color.LTGRAY,9f)}}
    private fun drawRuler(c:Canvas,r:RectF){if(ruler==0)return;ui.style=Paint.Style.STROKE;ui.color=Color.rgb(105,140,175);ui.strokeWidth=1f;when(ruler){1->c.drawLine(r.left,r.centerY(),r.right,r.centerY(),ui);2->c.drawCircle(r.centerX(),r.centerY(),min(r.width(),r.height())*.32f,ui);3->c.drawOval(r.centerX()-r.width()*.3f,r.centerY()-r.height()*.2f,r.centerX()+r.width()*.3f,r.centerY()+r.height()*.2f,ui);4->repeat(24){i->val a=i*PI/12;c.drawLine(r.centerX(),r.centerY(),r.centerX()+cos(a).toFloat()*r.width(),r.centerY()+sin(a).toFloat()*r.height(),ui)};5->c.drawLine(r.centerX(),r.top,r.centerX(),r.bottom,ui);6,7->repeat(symmetry){i->c.save();c.rotate(i*360f/symmetry,r.centerX(),r.centerY());c.drawLine(r.centerX(),r.centerY(),r.right,r.centerY(),ui);c.restore()};8->repeat(4){i->c.drawLine(r.left+r.width()*(i+1)/5f,r.top,r.left+r.width()*(i+1)/5f,r.bottom,ui)};9->{val vx=r.centerX();val vy=r.top-80f;repeat(9){i->val xx=r.left+r.width()*i/8f;c.drawLine(vx,vy,xx,r.bottom,ui)}}};ui.style=Paint.Style.FILL}
    private fun canvasRect()=RectF(if(panel==null)72f else 190f,155f,width.toFloat()-(if(panel==null)20f else 310f),height.toFloat()-8f)
    private fun editorMatrix(r:RectF)=Matrix().apply{set(viewport.matrix(r.centerX(),r.centerY()));postTranslate(cameraX,cameraY);postScale(cameraScale,cameraScale,r.centerX(),r.centerY());postRotate(cameraRotation,r.centerX(),r.centerY())}
    private fun toDoc(x:Float,y:Float):PointF{val p=floatArrayOf(x,y);val inv=Matrix();if(editorMatrix(canvasRect()).invert(inv))inv.mapPoints(p);return PointF(p[0],p[1])}
    override fun onTouchEvent(e:MotionEvent):Boolean{if(colorPopup)return colorPopupTouch(e);if(dialog)return dialogTouch(e);if(menu)return menuTouch(e);if(mode==Mode.HOME)return homeTouch(e);if(e.pointerCount>=2){if(current!=null)finishStroke();when(e.actionMasked){MotionEvent.ACTION_POINTER_DOWN->viewport.beginGesture(e);MotionEvent.ACTION_MOVE->{viewport.updateGesture(e,settings.allowPinchZoom,settings.allowPinchRotation);invalidate()};MotionEvent.ACTION_POINTER_UP,MotionEvent.ACTION_UP,MotionEvent.ACTION_CANCEL->viewport.endGesture()};return true};when(e.actionMasked){MotionEvent.ACTION_DOWN->{if(handleUi(e.x,e.y))return true;if(tool==Tool.LASSO){lasso.clear();selectedStrokeIds.clear();lasso+=toDoc(e.x,e.y);return true};if(tool==Tool.FILL){fillAt(toDoc(e.x,e.y));return true};if(tool==Tool.PAN||tool==Tool.TRANSFORM){gestureStart=PointF(e.x,e.y);return true};if(canvasRect().contains(e.x,e.y))beginStroke(e)};MotionEvent.ACTION_MOVE->{if(tool==Tool.LASSO){lasso+=toDoc(e.x,e.y);invalidate();return true};if(gestureStart!=null&&(tool==Tool.PAN||tool==Tool.TRANSFORM)){applyPanTransform(e);return true};if(current!=null)addSample(e)};MotionEvent.ACTION_UP,MotionEvent.ACTION_CANCEL->{if(tool==Tool.LASSO){if(lasso.size>2){lasso+=lasso.first();selectLasso()};invalidate();return true};if(current!=null)finishStroke();gestureStart=null};};return true}
    private fun homeTouch(e:MotionEvent):Boolean{if(e.actionMasked!=MotionEvent.ACTION_UP)return true;if(e.x>width-210f&&e.y>height-100f){dialog=true;invalidate();return true};if(ProjectStore.projects.isNotEmpty()&&e.y in 80f..230f){project=ProjectStore.projects.first();loadProject(project!!);mode=Mode.EDITOR;invalidate()};return true}
    private fun handleUi(x:Float,y:Float):Boolean{if(y<50f&&x<48f){menu=true;invalidate();return true};if(y<50f&&x>width-200f){openColorPopup();return true};if(y in 50f..150f){val f=((x-190f)/30f).roundToInt();if(f in 0 until document.duration){document.currentFrame=f;invalidate();return true}}
        if(x>=70f&&x<=180f&&y>=155f&&y<155f+6*53f){val i=((y-160f)/53f).toInt();if(i in Panel.values().indices){panel=if(panel==Panel.values()[i])null else Panel.values()[i];invalidate();return true}}
        if(x<62f&&y>=155f){val i=((y-160f)/41f).toInt();if(i in Tool.values().indices){tool=Tool.values()[i];if(panel==null)panel=Panel.OPTIONS;invalidate();return true}}
        val right=width.toFloat()-300f;if(panel==Panel.BRUSHES&&x>=right&&y>185f){selectBrush(y);return true};if(panel==Panel.RULERS&&x>=right&&y>185f){val i=((y-206f)/24f).toInt();if(i in 0..8)ruler=i+1;invalidate();return true};if(panel==Panel.CAMERA&&x>=right&&y in 285f..340f){resetCamera();invalidate();return true};if(panel==Panel.CAMERA&&x>=right&&y in 250f..284f){toggleCameraKey();return true};if(panel==Panel.LAYERS&&x>=right&&y in 185f..220f){addLayer();return true};if(panel==Panel.LAYERS&&x>=right&&y>220f){selectLayer(y);return true};if(panel==Panel.TIMELINE&&x>=right&&y in 220f..305f){document.onion.enabled=!document.onion.enabled;invalidate();return true};if(panel==Panel.OPTIONS&&x>=right&&y in 390f..430f){realTimeStabilizer=!realTimeStabilizer;invalidate();return true};if(panel==Panel.OPTIONS&&x>=right&&y in 430f..460f){antiAlias=!antiAlias;invalidate();return true};return false}
    private fun menuTouch(e:MotionEvent):Boolean{if(e.actionMasked!=MotionEvent.ACTION_UP)return true;if(e.x>275f){menu=false;invalidate();return true};when{e.y in 55f..120f->{mode=Mode.HOME;menu=false;invalidate()};e.y in 120f..185f->{menu=false;exportFormat=null;invalidate();showExportPanel()};e.y in 185f..250f->{(context as? MainActivity)?.pickVideo();menu=false};e.y in 250f..315f->{menu=false};e.y in 315f..380f->{(context as? MainActivity)?.pickVideo();menu=false};e.y in 380f..445f->{menu=false};e.y in 445f..510f->{menu=false};e.y in 510f..575f->{menu=false}};return true}
    private fun drawMenu(c:Canvas){ui.color=Color.argb(245,35,37,40);c.drawRect(0f,50f,275f,min(height-40f,625f),ui);val items=listOf("Close project","Export video","Import audio","Import image(s)","Import video","Import project","Change framerate","Resize or crop/expand");items.forEachIndexed{i,s->text(c,s,18f,92f+i*64f,Color.WHITE,12f)}}
    private fun showExportPanel(){dialog=true;invalidate()}
    private fun drawDialog(c:Canvas){ui.color=Color.argb(235,10,11,13);c.drawRect(0f,0f,width.toFloat(),height.toFloat(),ui);val l=width/2f-270f;val t=height/2f-220f;ui.color=Color.rgb(38,40,44);c.drawRoundRect(l,t,l+540f,t+440f,12f,12f,ui);if(exportFormat==null){text(c,"Export video",l+24f,t+38f,Color.WHITE,18f);text(c,"MP4 video",l+32f,t+100f,Color.WHITE,14f);text(c,"GIF animation",l+32f,t+165f,Color.WHITE,14f);text(c,"Image sequence (PNG)",l+32f,t+230f,Color.WHITE,14f);text(c,"Exports the complete playback range at project FPS.",l+32f,t+290f,Color.GRAY,10f)}else{text(c,"Export ${exportFormat!!.name}",l+24f,t+38f,Color.WHITE,18f);text(c,"${document.width} × ${document.height}   ${document.fps} FPS",l+24f,t+82f,Color.LTGRAY,11f);text(c,"Start frame: ${document.playbackStart+1}",l+24f,t+120f,Color.LTGRAY,11f);text(c,"End frame: ${document.playbackEnd+1}",l+24f,t+150f,Color.LTGRAY,11f);text(c,"Choose a destination file to begin export.",l+24f,t+205f,Color.GRAY,10f)};text(c,"Cancel",l+360f,t+400f,Color.LTGRAY,11f);if(exportFormat!=null)text(c,"Choose file",l+445f,t+400f,Color.WHITE,11f)}
    private fun dialogTouch(e:MotionEvent):Boolean{if(e.actionMasked!=MotionEvent.ACTION_UP)return true;val l=width/2f-270f;val t=height/2f-220f;if(exportFormat==null){when{e.y in t+55f..t+125f->exportFormat=AnimationExportEngine.Format.MP4;e.y in t+125f..t+190f->exportFormat=AnimationExportEngine.Format.GIF;e.y in t+190f..t+260f->exportFormat=AnimationExportEngine.Format.PNG_SEQUENCE};invalidate();return true};if(e.y>t+365f&&e.x>l+420f){(context as? MainActivity)?.createExport(exportFormat!!);dialog=false;return true};if(e.y>t+365f){dialog=false;exportFormat=null;invalidate();return true};return true}
    private fun openColorPopup(){previousColor=selectedColor;colorPopup=true;invalidate()}
    private fun drawColorPopup(c:Canvas){ui.color=Color.argb(210,0,0,0);c.drawRect(0f,0f,width.toFloat(),height.toFloat(),ui);val w=min(620f,width*.72f);val h=min(470f,height*.72f);val l=(width-w)/2f;val t=(height-h)/2f;ui.color=Color.rgb(38,40,44);c.drawRoundRect(l,t,l+w,t+h,12f,12f,ui);text(c,"COLOR",l+22f,t+32f,Color.WHITE,16f);ui.color=previousColor;c.drawRect(l+22f,t+48f,l+82f,t+88f,ui);ui.color=selectedColor;c.drawRect(l+88f,t+48f,l+148f,t+88f,ui);text(c,"PREVIOUS",l+22f,t+104f,Color.GRAY,8f);text(c,"CURRENT",l+88f,t+104f,Color.GRAY,8f);text(c,colorPaletteMode?"PALETTE":"HSB",l+w-120f,t+32f,Color.WHITE,10f)
        if(colorPaletteMode){var i=0;palette.forEach{col->val px=l+24f+(i%8)*68f;val py=t+130f+(i/8)*58f;ui.color=col;c.drawRoundRect(px,py,px+50f,py+40f,5f,5f,ui);i++};text(c,"HISTORY",l+24f,t+h-70f,Color.LTGRAY,9f);colorHistory.take(12).forEachIndexed{j,col->ui.color=col;c.drawCircle(l+28f+j*40f,t+h-40f,14f,ui)}}else{drawHsbPicker(c,l+24f,t+130f,280f,220f);text(c,"H: ${hueOf(selectedColor).roundToInt()}°",l+330f,t+145f,Color.LTGRAY,11f);text(c,"S: ${(satOf(selectedColor)*100).roundToInt()}%",l+330f,t+175f,Color.LTGRAY,11f);text(c,"B: ${(valueOf(selectedColor)*100).roundToInt()}%",l+330f,t+205f,Color.LTGRAY,11f);text(c,"A: ${Color.alpha(selectedColor)}",l+330f,t+235f,Color.LTGRAY,11f);text(c,String.format("#%08X",selectedColor),l+330f,t+275f,Color.WHITE,14f);text(c,"TAP PALETTE",l+330f,t+330f,Color.WHITE,10f);text(c,"TAP OUTSIDE TO CLOSE",l+330f,t+360f,Color.GRAY,8f)}}
    private fun drawHsbPicker(c:Canvas,l:Float,t:Float,w:Float,h:Float){val bmp=Bitmap.createBitmap(w.toInt(),h.toInt(),Bitmap.Config.ARGB_8888);val pix=IntArray(bmp.width*bmp.height);val hsv=FloatArray(3);Color.colorToHSV(selectedColor,hsv);for(y in 0 until bmp.height)for(x in 0 until bmp.width){hsv[1]=x.toFloat()/max(1,bmp.width-1);hsv[2]=1f-y.toFloat()/max(1,bmp.height-1);pix[y*bmp.width+x]=Color.HSVToColor(Color.alpha(selectedColor),hsv)};bmp.setPixels(pix,0,bmp.width,0,0,bmp.width,bmp.height);c.drawBitmap(bmp,l,t,null);bmp.recycle();ui.style=Paint.Style.STROKE;ui.color=Color.WHITE;ui.strokeWidth=2f;val hsv2=FloatArray(3);Color.colorToHSV(selectedColor,hsv2);c.drawCircle(l+hsv2[1]*w,t+(1f-hsv2[2])*h,8f,ui);ui.style=Paint.Style.FILL}
    private fun colorPopupTouch(e:MotionEvent):Boolean{if(e.actionMasked!=MotionEvent.ACTION_UP&&e.actionMasked!=MotionEvent.ACTION_MOVE)return true;val w=min(620f,width*.72f);val h=min(470f,height*.72f);val l=(width-w)/2f;val t=(height-h)/2f;if(e.actionMasked==MotionEvent.ACTION_UP&&(!RectF(l,t,l+w,t+h).contains(e.x,e.y))){colorPopup=false;invalidate();return true};if(e.y in t+110f..t+h-90f&&e.x in l+15f..l+320f&&!colorPaletteMode){val nx=((e.x-(l+24f))/280f).coerceIn(0f,1f);val ny=((e.y-(t+130f))/220f).coerceIn(0f,1f);val hsv=FloatArray(3);Color.colorToHSV(selectedColor,hsv);hsv[1]=nx;hsv[2]=1f-ny;setSelectedColor(Color.HSVToColor(Color.alpha(selectedColor),hsv));invalidate();return true};if(e.actionMasked==MotionEvent.ACTION_UP&&e.y in t+115f..t+h-95f&&e.x>l+330f&&!colorPaletteMode){colorPaletteMode=true;invalidate();return true};if(e.actionMasked==MotionEvent.ACTION_UP&&colorPaletteMode){var i=0;palette.forEach{col->val px=l+24f+(i%8)*68f;val py=t+130f+(i/8)*58f;if(e.x in px..px+50f&&e.y in py..py+40f){setSelectedColor(col);return true};i++}};return true}
    private fun setSelectedColor(c:Int){previousColor=selectedColor;selectedColor=c;while(colorHistory.contains(c))colorHistory.remove(c);colorHistory.addFirst(c);while(colorHistory.size>100)colorHistory.removeLast()}
    private fun hueOf(c:Int):Float{val h=FloatArray(3);Color.colorToHSV(c,h);return h[0]};private fun satOf(c:Int):Float{val h=FloatArray(3);Color.colorToHSV(c,h);return h[1]};private fun valueOf(c:Int):Float{val h=FloatArray(3);Color.colorToHSV(c,h);return h[2]}
    private fun isSmoothEnabled()=true
    private fun loadProject(p:AnimationProject){fps=p.fps;cw=p.cameraWidth;ch=p.cameraHeight;document=AnimationDocument(name=p.name,width=p.canvasWidth,height=p.canvasHeight,fps=p.fps);selectedLayerId=document.activeLayer.id;viewport.reset();resetCamera();history.clear();bitmapCache.clear()}
    private fun beginStroke(e:MotionEvent){samples.clear();lowLatency.reset();current=Path();val p=lowLatency.update(toDoc(e.x,e.y),e.eventTime);samples+=Stabilizer.Sample(p,e.pressure.coerceIn(.05f,1.5f),e.eventTime,e.tilt);lastPoint=p;lastTime=e.eventTime;current!!.moveTo(p.x,p.y);invalidate()}
    private fun addSample(e:MotionEvent){if(!canvasRect().contains(e.x,e.y))return;for(i in 0 until e.historySize){val p=lowLatency.update(toDoc(e.getHistoricalX(i),e.getHistoricalY(i)),e.getHistoricalEventTime(i));samples+=Stabilizer.Sample(p,e.getHistoricalPressure(i).coerceIn(.05f,1.5f),e.getHistoricalEventTime(i),e.getHistoricalOrientation(i))};val p=lowLatency.update(toDoc(e.x,e.y),e.eventTime);samples+=Stabilizer.Sample(p,e.pressure.coerceIn(.05f,1.5f),e.eventTime,e.tilt);val prev=lastPoint;val dt=e.eventTime-lastTime;val speed=if(prev!=null&&dt>0)Stabilizer.distance(prev,p)*1000f/dt else 0f;current=Stabilizer.smoothSamples(samples,if(realTimeStabilizer)Stabilizer.adaptiveStrength(speed,stabilizer*.25f,stabilizer) else stabilizer,realTimeStabilizer);lastPoint=p;lastTime=e.eventTime;invalidate()}
    private fun finishStroke(){if(samples.isEmpty()){current=null;return};val layer=document.layers.firstOrNull{it.id==selectedLayerId}?:return;if(layer.locked){samples.clear();current=null;return};val frame=layer.ensureFrame(document.currentFrame);val generated=when(tool){Tool.LINE->shapeSamplesLine(samples.first().point,samples.last().point);Tool.RECTANGLE->shapeSamplesRect(samples.first().point,samples.last().point);Tool.ELLIPSE->shapeSamplesEllipse(samples.first().point,samples.last().point);else->samples.map{StrokeSample(it.point.x,it.point.y,it.pressure,it.timeMs,it.tilt)}};val preset=if(tool==Tool.PENCIL)"pencil" else selectedBrush.id;val bs=brushSettings.copy(size=brushSize,opacity=opacity,eraser=tool==Tool.ERASER).normalized();val d=StrokeData(brushId=preset,color=selectedColor,size=brushSize,opacity=opacity,brushSettings=bs,samples=generated.toMutableList());history.execute(LambdaCommand({frame.strokes.add(d)},{frame.strokes.removeAll{it.id==d.id}}));setSelectedColor(selectedColor);samples.clear();current=null;invalidate()}
    private fun shapeSamplesLine(a:PointF,b:PointF)=listOf(StrokeSample(a.x,a.y),StrokeSample(b.x,b.y))
    private fun shapeSamplesRect(a:PointF,b:PointF):List<StrokeSample>{val l=min(a.x,b.x);val r=max(a.x,b.x);val t=min(a.y,b.y);val bot=max(a.y,b.y);return listOf(PointF(l,t),PointF(r,t),PointF(r,bot),PointF(l,bot),PointF(l,t)).map{StrokeSample(it.x,it.y)}}
    private fun shapeSamplesEllipse(a:PointF,b:PointF):List<StrokeSample>{val cx=(a.x+b.x)/2;val cy=(a.y+b.y)/2;val rx=abs(b.x-a.x)/2;val ry=abs(b.y-a.y)/2;return (0..64).map{val q=it*2*PI/64;StrokeSample((cx+cos(q)*rx).toFloat(),(cy+sin(q)*ry).toFloat())}}
    private fun fillAt(p:PointF){val layer=document.layers.firstOrNull{it.id==selectedLayerId}?:return;if(layer.locked)return;val frame=layer.ensureFrame(document.currentFrame);val b=Bitmap.createBitmap(document.width,document.height,Bitmap.Config.ARGB_8888);val cc=Canvas(b);cc.drawColor(Color.TRANSPARENT,PorterDuff.Mode.CLEAR);frame.strokes.forEach{drawStroke(cc,it)};val sx=p.x.roundToInt().coerceIn(0,b.width-1);val sy=p.y.roundToInt().coerceIn(0,b.height-1);if(BucketEngine.fill(b,sx,sy,selectedColor)){val file=java.io.File(context.filesDir,"fills/${System.currentTimeMillis()}_${document.currentFrame}.png");file.parentFile?.mkdirs();java.io.FileOutputStream(file).use{b.compress(Bitmap.CompressFormat.PNG,100,it)};frame.strokes.clear();frame.rasterPath=file.absolutePath;bitmapCache[file.absolutePath]=b}else b.recycle();invalidate()}
    private fun selectLasso(){selectedStrokeIds.clear();val layer=document.layers.firstOrNull{it.id==selectedLayerId}?:return;layer.frameAt(document.currentFrame)?.strokes?.forEach{s->if(s.samples.any{LassoEngine.contains(lasso,PointF(it.x,it.y))})selectedStrokeIds+=s.id}}
    private fun applyPanTransform(e:MotionEvent){val s=gestureStart?:return;val dx=e.x-s.x;val dy=e.y-s.y;if(tool==Tool.PAN){cameraX+=dx;cameraY+=dy}else{if(selectedStrokeIds.isNotEmpty()){val d=toDoc(e.x,e.y);val old=toDoc(s.x,s.y);val ox=d.x-old.x;val oy=d.y-old.y;document.layers.firstOrNull{it.id==selectedLayerId}?.frameAt(document.currentFrame)?.strokes?.filter{selectedStrokeIds.contains(it.id)}?.forEach{st->st.samples.forEachIndexed{i,sm->st.samples[i]=sm.copy(x=sm.x+ox,y=sm.y+oy)}}}else{cameraScale=(cameraScale*(1f+dy*.005f)).coerceIn(.1f,8f);cameraRotation=(cameraRotation+dx*.25f)%360f}};gestureStart=PointF(e.x,e.y);invalidate()}
    private fun selectBrush(y:Float){var yy=206f;for(f in BrushCatalog.families){yy+=18f;for(p in BrushCatalog.presets.filter{it.family==f}){if(y in yy-16f..yy+2f){selectedBrush=p;brushSettings=p.defaults.copy();brushSize=brushSettings.size;opacity=brushSettings.opacity;panel=Panel.OPTIONS;invalidate();return};yy+=16f};yy+=4f}}
    private fun addLayer(){val l=document.addLayer();selectedLayerId=l.id;invalidate()};private fun selectLayer(y:Float){val i=((y-220f)/30f).toInt();if(i in document.layers.indices)selectedLayerId=document.layers[i].id;invalidate()};private fun toggleCameraKey(){val i=document.cameraKeys.indexOfFirst{it.frame==document.currentFrame};if(i>=0)document.cameraKeys.removeAt(i)else document.cameraKeys+=CameraKeyframe(document.currentFrame,AnimationCamera(cameraX,cameraY,cameraScale,cameraRotation));invalidate()};private fun resetCamera(){cameraX=0f;cameraY=0f;cameraScale=1f;cameraRotation=0f}
    fun importVideo(uri:Uri){Thread{try{val result=VideoImportEngine.importVideo(context,uri);post{val layer=document.addLayer("Video import");result.framePaths.forEachIndexed{i,path->layer.frames[i]=DrawingFrame(rasterPath=path)};document.duration=maxOf(document.duration,result.frameCount);document.playbackEnd=document.duration-1;document.fps=result.fps;document.width=result.width;document.height=result.height;selectedLayerId=layer.id;invalidate()}}catch(_:Throwable){post{invalidate()}}}.start()}
    fun exportVideo(uri:Uri,format:AnimationExportEngine.Format){Thread{try{AnimationExportEngine.export(context,uri,format,AnimationExportEngine.Settings(document.width,document.height,document.fps,document.playbackStart,document.playbackEnd)){f->renderFrameBitmap(f)}}catch(_:Throwable){}}.start()}
    private fun renderFrameBitmap(frame:Int):Bitmap{val b=Bitmap.createBitmap(document.width,document.height,Bitmap.Config.ARGB_8888);val c=Canvas(b);c.drawColor(Color.WHITE);document.layers.asReversed().filter{it.visible}.forEach{l->l.frameAt(frame)?.let{f->drawRaster(c,f);f.strokes.forEach{s->drawStroke(c,s)}}};return b}
    private fun text(c:Canvas,s:String,x:Float,y:Float,color:Int,size:Float){ui.style=Paint.Style.FILL;ui.color=color;ui.textSize=size;ui.typeface=Typeface.create("sans",Typeface.NORMAL);c.drawText(s,x,y,ui)}
}