package com.animame.editor

import android.content.Context
import android.graphics.*
import android.view.MotionEvent
import android.view.View
import kotlin.math.*

class AnimationEditorViewV5(context: Context) : View(context) {
    private enum class Mode { HOME, EDITOR }
    private enum class Panel { OPTIONS, BRUSHES, LAYERS, TIMELINE, CAMERA, RULERS }
    private var mode=Mode.HOME; private var panel:Panel?=Panel.OPTIONS; private var dialog=false
    private var project:AnimationProject?=null; private var document=AnimationDocument(); private var projectName="Untitled"
    private var fps=24; private var cw=1280; private var ch=720; private var margin=0; private var selectedLayerId=document.activeLayer.id
    private var selectedBrush=BrushCatalog.presets.first(); private var brushSize=12f; private var opacity=1f; private var stabilizer=55f
    private var realTimeStabilizer=true; private var antiAlias=true; private var ruler=0; private var symmetry=6; private var playing=false; private var lastPlayTime=0L; private var frameAccumulator=0f
    private val viewport=CanvasViewport(); private val settings get()=EditorSettingsStore.current; private val history=EditorHistory(120); private val lowLatency=LowLatencyStabilizer()
    private var cameraX=0f; private var cameraY=0f; private var cameraScale=1f; private var cameraRotation=0f
    private val samples=mutableListOf<Stabilizer.Sample>(); private var current:Path?=null; private var lastPoint:PointF?=null; private var lastTime=0L; private val ui=Paint(Paint.ANTI_ALIAS_FLAG)
    init{setLayerType(View.LAYER_TYPE_SOFTWARE,null)}
    override fun onDraw(c:Canvas){if(mode==Mode.HOME)drawHome(c)else drawEditor(c);if(dialog)drawDialog(c);if(playing){val now=System.currentTimeMillis();if(lastPlayTime==0L)lastPlayTime=now;frameAccumulator+=(now-lastPlayTime)/1000f*document.fps;lastPlayTime=now;while(frameAccumulator>=1f){document.currentFrame++;frameAccumulator-=1f;if(document.currentFrame>document.playbackEnd)document.currentFrame=document.playbackStart};postInvalidateDelayed(16)}}
    private fun bg(c:Canvas){ui.style=Paint.Style.FILL;ui.color=Color.rgb(16,17,19);c.drawRect(0f,0f,width.toFloat(),height.toFloat(),ui)}
    private fun drawHome(c:Canvas){bg(c);ui.color=Color.rgb(27,29,32);c.drawRect(0f,0f,width.toFloat(),54f,ui);text(c,"ANIMA-ME",22f,35f,Color.WHITE,18f);text(c,"Sort by date",width-115f,35f,Color.LTGRAY,10f);if(ProjectStore.projects.isEmpty())text(c,"No projects",width/2f-35f,height/2f,Color.LTGRAY,14f)else{var y=80f;ProjectStore.projects.forEach{p->ui.color=Color.rgb(36,39,43);c.drawRoundRect(24f,y,300f,y+150f,8f,8f,ui);text(c,p.name,40f,y+122f,Color.WHITE,12f);text(c,"${p.fps} fps   ${p.cameraWidth} x ${p.cameraHeight}",40f,y+141f,Color.GRAY,9f);y+=170f}};ui.color=Color.rgb(52,55,60);c.drawRoundRect(width-190f,height-76f,width-24f,height-26f,10f,10f,ui);text(c,"New project",width-154f,height-45f,Color.WHITE,12f)}
    private fun drawDialog(c:Canvas){ui.color=Color.argb(235,10,11,13);c.drawRect(0f,0f,width.toFloat(),height.toFloat(),ui);val l=width/2f-250f;val t=height/2f-195f;ui.color=Color.rgb(38,40,44);c.drawRoundRect(l,t,l+500f,t+390f,12f,12f,ui);text(c,"New project",l+24f,t+35f,Color.WHITE,17f);field(c,"New project name",projectName,l+24f,t+68f);field(c,"Frames per second",fps.toString(),l+24f,t+126f);field(c,"Camera size","${cw} x ${ch}",l+24f,t+184f);field(c,"Margins",margin.toString(),l+24f,t+242f);field(c,"Canvas size","${cw+margin*2} x ${ch+margin*2}",l+24f,t+300f);text(c,"Cancel",l+300f,t+356f,Color.LTGRAY,11f);text(c,"New project",l+395f,t+356f,Color.WHITE,11f)}
    private fun field(c:Canvas,a:String,b:String,x:Float,y:Float){text(c,a,x,y,Color.GRAY,8f);text(c,b,x,y+22f,Color.WHITE,12f);ui.color=Color.rgb(66,69,74);c.drawRect(x,y+29f,x+450f,y+30f,ui)}
    private fun drawEditor(c:Canvas){bg(c);val w=width.toFloat();val h=height.toFloat();ui.color=Color.rgb(27,29,32);c.drawRect(0f,0f,w,50f,ui);text(c,"ANIMA-ME",14f,32f,Color.WHITE,15f);text(c,project?.name?:"Untitled",116f,32f,Color.LTGRAY,12f);text(c,"${document.fps} FPS",w-116f,32f,Color.LTGRAY,12f);val r=canvasRect();ui.color=Color.WHITE;c.drawRect(r,ui);c.save();c.clipRect(r);c.concat(viewport.matrix(r.centerX(),r.centerY()));c.translate(cameraX,cameraY);c.scale(cameraScale,cameraScale,r.centerX(),r.centerY());c.rotate(cameraRotation,r.centerX(),r.centerY());drawOnion(c);drawCurrentFrame(c);current?.let{c.drawPath(it,brushPaint())};c.restore();drawRuler(c,r);tabs(c);rail(c);if(panel!=null)drawPanel(c,w-300f,h);timeline(c,h)}
    private fun drawCurrentFrame(c:Canvas){document.layers.asReversed().filter{it.visible}.forEach{layer->layer.frameAt(document.currentFrame)?.strokes?.forEach{s->drawStroke(c,s)}}}
    private fun drawOnion(c:Canvas){if(!document.onion.enabled)return;val layer=document.layers.firstOrNull{it.id==selectedLayerId}?:return;val alpha=(document.onion.opacity*2.55f).roundToInt().coerceIn(0,255);layer.previousFrames(document.currentFrame,document.onion.previousCount).forEach{(_,f)->f.strokes.forEach{s->drawStroke(c,s,if(document.onion.tintPrevious)Color.argb(alpha,80,150,255)else null)}};layer.nextFrames(document.currentFrame,document.onion.nextCount).forEach{(_,f)->f.strokes.forEach{s->drawStroke(c,s,if(document.onion.tintNext)Color.argb(alpha,255,110,110)else null)}}}
    private fun drawStroke(c:Canvas,s:StrokeData,tint:Int?=null){if(s.samples.isEmpty())return;val path=Stabilizer.smoothSamples(s.samples.map{Stabilizer.Sample(PointF(it.x,it.y),it.pressure,it.timeMs)},0f,false);val p=Paint(Paint.ANTI_ALIAS_FLAG).apply{style=Paint.Style.STROKE;color=tint?:s.color;strokeWidth=s.size;strokeCap=Paint.Cap.ROUND;strokeJoin=Paint.Join.ROUND;alpha=(s.opacity*255f).roundToInt().coerceIn(1,255)};c.drawPath(path,p)}
    private fun tabs(c:Canvas){listOf("OPTIONS","BRUSHES","LAYERS","TIMELINE","CAMERA","RULERS").forEachIndexed{i,n->{val x=190f+i*78f;ui.color=if(panel==Panel.values()[i])Color.rgb(68,73,81)else Color.rgb(43,46,50);c.drawRoundRect(x,9f,x+74f,41f,7f,7f,ui);text(c,n,x+7f,29f,Color.WHITE,8f)}}}
    private fun rail(c:Canvas){ui.color=Color.rgb(31,33,36);c.drawRect(0f,50f,62f,height-112f,ui);listOf("BR","PE","ER","LA","FI","PI","MV","TR","LN","RE","EL").forEachIndexed{i,n->text(c,n,19f,78f+i*41f,Color.WHITE,9f)}}
    private fun drawPanel(c:Canvas,x:Float,h:Float){ui.color=Color.rgb(29,31,34);c.drawRect(x,50f,width.toFloat(),h-112f,ui);text(c,when(panel){Panel.OPTIONS->"TOOL OPTIONS";Panel.BRUSHES->"BRUSH LIBRARY";Panel.LAYERS->"LAYERS";Panel.TIMELINE->"TIMELINE";Panel.CAMERA->"CAMERA / TRANSFORM";Panel.RULERS->"RULERS";null->""},x+14f,78f,Color.WHITE,13f);when(panel){Panel.OPTIONS->options(c,x+14f);Panel.BRUSHES->brushes(c,x+14f);Panel.LAYERS->layers(c,x+14f);Panel.TIMELINE->timelinePanel(c,x+14f);Panel.CAMERA->camera(c,x+14f);Panel.RULERS->rulers(c,x+14f);null->Unit}}
    private fun options(c:Canvas,x:Float){text(c,"BRUSH  ${selectedBrush.name}",x,108f,Color.WHITE,12f);text(c,"SIZE  ${brushSize.roundToInt()} px",x,138f,Color.LTGRAY,11f);text(c,"OPACITY  ${(opacity*100).roundToInt()}%",x,166f,Color.LTGRAY,11f);text(c,"SMOOTHING  ${stabilizer.roundToInt()}%",x,194f,Color.LTGRAY,11f);text(c,"STABILIZER  ${if(realTimeStabilizer)"REAL TIME" else "AFTER"}",x,222f,Color.LTGRAY,10f);text(c,"ANTI-ALIAS  ${if(antiAlias)"ON" else "OFF"}",x,248f,Color.LTGRAY,10f);text(c,"VIEW ZOOM  ${(viewport.scale*100).roundToInt()}%",x,276f,Color.LTGRAY,10f);text(c,"VIEW ROTATION  ${viewport.rotation.roundToInt()}°",x,300f,Color.LTGRAY,10f);text(c,"PINCH ZOOM ${if(settings.allowPinchZoom)"ON" else "OFF"}",x,326f,Color.GRAY,9f);text(c,"PINCH ROTATION ${if(settings.allowPinchRotation)"ON" else "OFF"}",x,346f,Color.GRAY,9f);text(c,"UNDO ${if(history.canUndo)"READY" else "EMPTY"}   REDO ${if(history.canRedo)"READY" else "EMPTY"}",x,374f,Color.GRAY,9f)}
    private fun brushes(c:Canvas,x:Float){var y=108f;BrushCatalog.families.forEach{f->if(y<height-135){text(c,f,x,y,Color.WHITE,10f);y+=18f;BrushCatalog.presets.filter{it.family==f}.forEach{p->if(y<height-135){text(c,if(p.id==selectedBrush.id)"• ${p.name}" else "  ${p.name}",x+6f,y,if(p.id==selectedBrush.id)Color.WHITE else Color.GRAY,9f);y+=16f}};y+=4f}}}
    private fun layers(c:Canvas,x:Float){text(c,"+ NEW LAYER",x,108f,Color.WHITE,10f);var y=138f;document.layers.forEach{l->text(c,if(l.id==selectedLayerId)"• ${l.name}" else "  ${l.name}",x,y,Color.LTGRAY,10f);text(c,"${if(l.visible)"VISIBLE" else "HIDDEN"}  ${if(l.locked)"LOCKED" else "UNLOCKED"}",x+115f,y,Color.GRAY,8f);y+=30f};text(c,"DELETE SELECTED",x,y+10f,Color.GRAY,9f)}
    private fun timelinePanel(c:Canvas,x:Float){text(c,"CURRENT FRAME  ${document.currentFrame+1} / ${document.duration}",x,108f,Color.WHITE,10f);text(c,"ONION SKIN   ${if(document.onion.enabled)"ON" else "OFF"}",x,136f,Color.LTGRAY,10f);text(c,"PREVIOUS ${document.onion.previousCount}   NEXT ${document.onion.nextCount}",x,164f,Color.LTGRAY,10f);text(c,"PLAYBACK ${document.playbackStart+1} - ${document.playbackEnd+1}",x,192f,Color.LTGRAY,10f)}
    private fun camera(c:Canvas,x:Float){text(c,"POSITION  ${cameraX.roundToInt()}, ${cameraY.roundToInt()}",x,108f,Color.LTGRAY,10f);text(c,"SCALE  ${(cameraScale*100).roundToInt()}%",x,136f,Color.LTGRAY,10f);text(c,"ROTATION  ${cameraRotation.roundToInt()}°",x,164f,Color.LTGRAY,10f);text(c,"KEYFRAME  ${if(document.cameraKeys.any{it.frame==document.currentFrame})"ON" else "OFF"}",x,192f,Color.LTGRAY,10f);text(c,"RESET CAMERA",x,220f,Color.WHITE,10f);text(c,"VIEWPORT  ${(viewport.scale*100).roundToInt()}% / ${viewport.rotation.roundToInt()}°",x,248f,Color.GRAY,9f)}
    private fun rulers(c:Canvas,x:Float){listOf("STRAIGHT RULER","CIRCULAR RULER","ELLIPSE RULER","RADIAL RULER","MIRROR RULER","KALEIDOSCOPE RULER","ROTATION RULER","ARRAY RULER","PERSPECTIVE ARRAY RULER").forEachIndexed{i,s->text(c,if(ruler==i+1)"• $s" else "  $s",x,108f+i*24f,if(ruler==i+1)Color.WHITE else Color.LTGRAY,9f)}}
    private fun drawRuler(c:Canvas,r:RectF){if(ruler==0)return;ui.style=Paint.Style.STROKE;ui.isAntiAlias=true;ui.color=Color.rgb(105,140,175);ui.strokeWidth=1f;when(ruler){1->c.drawLine(r.left,r.centerY(),r.right,r.centerY(),ui);2->c.drawCircle(r.centerX(),r.centerY(),min(r.width(),r.height())*.32f,ui);3->c.drawOval(r.centerX()-r.width()*.3f,r.centerY()-r.height()*.2f,r.centerX()+r.width()*.3f,r.centerY()+r.height()*.2f,ui);4->repeat(24){i->val a=i*PI/12;c.drawLine(r.centerX(),r.centerY(),r.centerX()+cos(a).toFloat()*r.width(),r.centerY()+sin(a).toFloat()*r.height(),ui)};5->c.drawLine(r.centerX(),r.top,r.centerX(),r.bottom,ui);6,7->repeat(symmetry){i->c.save();c.rotate(i*360f/symmetry,r.centerX(),r.centerY());c.drawLine(r.centerX(),r.centerY(),r.centerX(),r.top,ui);c.restore()};8->repeat(4){i->c.drawLine(r.left+r.width()*(i+1)/5f,r.top,r.left+r.width()*(i+1)/5f,r.bottom,ui)};9->{val vx=r.centerX();val vy=r.top-80f;repeat(9){i->val xx=r.left+r.width()*i/8f;c.drawLine(vx,vy,xx,r.bottom,ui)}}};ui.style=Paint.Style.FILL}
    private fun timeline(c:Canvas,h:Float){ui.color=Color.rgb(27,29,32);c.drawRect(0f,h-112f,width.toFloat(),h,ui);text(c,"LAYERS",12f,h-88f,Color.LTGRAY,10f);text(c,"FRAME ${document.currentFrame+1}/${document.duration}",12f,h-62f,Color.WHITE,10f);val start=82f;val cell=28f;for(i in 0 until min(document.duration,24)){val x=start+i*cell;ui.color=if(i==document.currentFrame)Color.rgb(75,80,88)else Color.rgb(43,46,50);c.drawRect(x,h-102f,x+cell-2f,h-70f,ui);text(c,"${i+1}",x+8f,h-80f,Color.LTGRAY,8f)};text(c,"|<   <   ${if(playing)"STOP" else "PLAY"}   >   >|",width-175f,h-38f,Color.WHITE,10f)}
    private fun brushPaint(pressure:Float=1f)=Paint(Paint.ANTI_ALIAS_FLAG).apply{style=Paint.Style.STROKE;color=Color.BLACK;isAntiAlias=antiAlias;strokeWidth=(brushSize*pressure.coerceIn(.2f,1.5f)).coerceAtLeast(.5f);strokeCap=Paint.Cap.ROUND;strokeJoin=Paint.Join.ROUND;alpha=(opacity*255f).roundToInt().coerceIn(1,255)}
    private fun canvasRect()=RectF(72f,60f,width.toFloat()-(if(panel==null)72f else 310f),height.toFloat()-122f)
    override fun onTouchEvent(e:MotionEvent):Boolean{if(dialog)return dialogTouch(e);if(mode==Mode.HOME)return homeTouch(e);if(e.pointerCount>=2){if(current!=null)finishStroke();when(e.actionMasked){MotionEvent.ACTION_POINTER_DOWN->viewport.beginGesture(e);MotionEvent.ACTION_MOVE->{viewport.updateGesture(e);invalidate()};MotionEvent.ACTION_POINTER_UP->viewport.endGesture();MotionEvent.ACTION_UP,MotionEvent.ACTION_CANCEL->viewport.endGesture()};return true};when(e.actionMasked){MotionEvent.ACTION_DOWN->{if(handleUi(e.x,e.y))return true;if(canvasRect().contains(e.x,e.y))beginStroke(e);return true};MotionEvent.ACTION_MOVE->{if(current!=null)addSample(e);return true};MotionEvent.ACTION_UP,MotionEvent.ACTION_CANCEL->{if(current!=null)finishStroke();return true}};return true}
    private fun homeTouch(e:MotionEvent):Boolean{if(e.actionMasked!=MotionEvent.ACTION_UP)return true;if(e.x>width-210f&&e.y>height-100f){dialog=true;invalidate();return true};if(ProjectStore.projects.isNotEmpty()&&e.y in 80f..230f){project=ProjectStore.projects.first();loadProject(project!!);mode=Mode.EDITOR;invalidate()};return true}
    private fun loadProject(p:AnimationProject){fps=p.fps;cw=p.cameraWidth;ch=p.cameraHeight;document=AnimationDocument(name=p.name,width=p.canvasWidth,height=p.canvasHeight,fps=p.fps);selectedLayerId=document.activeLayer.id;viewport.reset();resetCamera();history.clear()}
    private fun handleUi(x:Float,y:Float):Boolean{if(y<48f&&x>=190f){val i=((x-190f)/78f).toInt();if(i in Panel.values().indices){panel=if(panel==Panel.values()[i])null else Panel.values()[i];invalidate();return true}};if(x<62f&&y in 50f..height-112f){panel=Panel.OPTIONS;invalidate();return true};val right=width.toFloat()-300f;if(panel==Panel.BRUSHES&&x>=right&&y>90f){selectBrush(y);return true};if(panel==Panel.RULERS&&x>=right&&y>90f){val i=((y-108f)/24f).toInt();if(i in 0..8)ruler=i+1;panel=Panel.OPTIONS;invalidate();return true};if(panel==Panel.CAMERA&&x>=right&&y in 180f..235f){resetCamera();invalidate();return true};if(panel==Panel.CAMERA&&x>=right&&y in 150f..205f){toggleCameraKey();return true};if(panel==Panel.LAYERS&&x>=right&&y in 90f..125f){addLayer();return true};if(panel==Panel.LAYERS&&x>=right&&y>125f){selectLayer(y);return true};if(panel==Panel.TIMELINE&&x>=right&&y>90f){document.onion.enabled=!document.onion.enabled;invalidate();return true};if(panel==Panel.OPTIONS&&x>=right&&y in 190f..240f){realTimeStabilizer=!realTimeStabilizer;invalidate();return true};if(panel==Panel.OPTIONS&&x>=right&&y in 240f..285f){antiAlias=!antiAlias;invalidate();return true};if(y>height-112f){handleTimelineTouch(x,y);return true};return false}
    private fun handleTimelineTouch(x:Float,y:Float){val h=height.toFloat();if(y>h-55f&&x>width-190f){playing=!playing;lastPlayTime=System.currentTimeMillis();invalidate();return};val frame=((x-82f)/28f).roundToInt();if(frame in 0 until document.duration){document.currentFrame=frame;invalidate()}}
    private fun beginStroke(e:MotionEvent){samples.clear();lowLatency.reset();current=Path();val p=toDoc(e.x,e.y);val now=e.eventTime;val fp=lowLatency.update(p,now);samples+=Stabilizer.Sample(fp,e.pressure.coerceIn(.05f,1.5f),now);lastPoint=fp;lastTime=now;current!!.moveTo(fp.x,fp.y);invalidate()}
    private fun addSample(e:MotionEvent){if(!canvasRect().contains(e.x,e.y))return;for(i in 0 until e.historySize){val hp=toDoc(e.getHistoricalX(i),e.getHistoricalY(i));val tm=e.getHistoricalEventTime(i);samples+=Stabilizer.Sample(lowLatency.update(hp,tm),e.getHistoricalPressure(i).coerceIn(.05f,1.5f),tm)};val p=toDoc(e.x,e.y);val fp=lowLatency.update(p,e.eventTime);samples+=Stabilizer.Sample(fp,e.pressure.coerceIn(.05f,1.5f),e.eventTime);val prev=lastPoint;val dt=e.eventTime-lastTime;val speed=if(prev!=null&&dt>0)Stabilizer.distance(prev,fp)*1000f/dt else 0f;val strength=Stabilizer.adaptiveStrength(speed,stabilizer*.45f,stabilizer);current=Stabilizer.smoothSamples(samples,if(realTimeStabilizer)strength else stabilizer,realTimeStabilizer);lastPoint=fp;lastTime=e.eventTime;invalidate()}
    private fun finishStroke(){if(samples.isEmpty()){current=null;return};val layer=document.layers.firstOrNull{it.id==selectedLayerId}?:document.activeLayer;val frame=layer.ensureFrame(document.currentFrame);val data=StrokeData(brushId=selectedBrush.id,color=Color.BLACK,size=brushSize,opacity=opacity,samples=samples.map{StrokeSample(it.point.x,it.point.y,it.pressure,it.timeMs)}.toMutableList());history.execute(LambdaCommand({frame.strokes.add(data)},{frame.strokes.removeAll{it.id==data.id}}));current=null;samples.clear();lastPoint=null;AutosaveManager.checkpoint(context,"${project?.name}|${document.currentFrame}|${document.duration}|${document.layers.size}");invalidate()}
    private fun toDoc(x:Float,y:Float):PointF{val r=canvasRect();return viewport.inversePoint(x,y,r.centerX(),r.centerY())}
    private fun selectBrush(y:Float){var yy=108f;for(f in BrushCatalog.families){yy+=18f;for(p in BrushCatalog.presets.filter{it.family==f}){if(y in yy-16f..yy+2f){selectedBrush=p;panel=Panel.OPTIONS;invalidate();return};yy+=16f};yy+=4f}}
    private fun addLayer(){val l=document.addLayer();selectedLayerId=l.id;invalidate()}
    private fun selectLayer(y:Float){val index=((y-125f)/30f).toInt();if(index in document.layers.indices)selectedLayerId=document.layers[index].id;invalidate()}
    private fun toggleCameraKey(){val i=document.cameraKeys.indexOfFirst{it.frame==document.currentFrame};if(i>=0)document.cameraKeys.removeAt(i)else document.cameraKeys.add(CameraKeyframe(document.currentFrame,AnimationCamera(cameraX,cameraY,cameraScale,cameraRotation)));invalidate()}
    private fun resetCamera(){cameraX=0f;cameraY=0f;cameraScale=1f;cameraRotation=0f}
    private fun dialogTouch(e:MotionEvent):Boolean{if(e.actionMasked!=MotionEvent.ACTION_UP)return true;val l=width/2f-250f;val t=height/2f-195f;if(e.x>l+380f&&e.y>t+325f){project=ProjectStore.create(projectName,fps,cw,ch,margin);loadProject(project!!);mode=Mode.EDITOR;dialog=false;invalidate();return true};if(e.x>l+270f&&e.x<l+370f&&e.y>t+325f){dialog=false;invalidate();return true};if(e.y in t+95f..t+150f){fps=when(fps){12->24;24->30;30->60;else->12};invalidate()};if(e.y in t+150f..t+210f){val sizes=arrayOf(1280 to 720,1920 to 1080,2048 to 1152,1080 to 1080);val idx=sizes.indexOfFirst{it.first==cw&&it.second==ch};val n=sizes[(idx+1).mod(sizes.size)];cw=n.first;ch=n.second;invalidate()};return true}
    private fun text(c:Canvas,s:String,x:Float,y:Float,color:Int,size:Float){ui.style=Paint.Style.FILL;ui.color=color;ui.textSize=size;ui.typeface=Typeface.create("sans",Typeface.NORMAL);c.drawText(s,x,y,ui)}
}