package com.animame.editor

import android.content.Context
import android.graphics.Bitmap
import android.graphics.Color
import android.media.MediaCodec
import android.media.MediaCodecInfo
import android.media.MediaExtractor
import android.media.MediaFormat
import android.media.MediaMetadataRetriever
import android.net.Uri
import android.os.Build
import java.io.File
import java.io.FileOutputStream
import java.util.zip.ZipEntry
import java.util.zip.ZipOutputStream
import kotlin.math.max
import kotlin.math.roundToInt

object VideoImportEngine {
 data class Result(val width:Int,val height:Int,val fps:Int,val frameCount:Int,val framePaths:List<String>,val durationUs:Long)
 fun importVideo(context:Context,uri:Uri,onProgress:(Int,Int)->Unit={_,_->}):Result{val r=MediaMetadataRetriever();r.setDataSource(context,uri);val width=r.extractMetadata(MediaMetadataRetriever.METADATA_KEY_VIDEO_WIDTH)?.toIntOrNull()?:1;val height=r.extractMetadata(MediaMetadataRetriever.METADATA_KEY_VIDEO_HEIGHT)?.toIntOrNull()?:1;val durationUs=(r.extractMetadata(MediaMetadataRetriever.METADATA_KEY_DURATION)?.toLongOrNull()?:0L)*1000L;val fps=extractFps(context,uri);val count=max(1,(durationUs/1_000_000.0*fps).roundToInt());val dir=File(context.filesDir,"imports/video_${System.currentTimeMillis()}").apply{mkdirs()};val paths=ArrayList<String>(count);for(i in 0 until count){val t=i*1_000_000L/fps;val b=if(Build.VERSION.SDK_INT>=28)runCatching{r.getFrameAtIndex(i)}.getOrNull() else null ?:runCatching{r.getFrameAtTime(t,MediaMetadataRetriever.OPTION_CLOSEST)}.getOrNull();if(b!=null){val f=File(dir,"frame_%06d.png".format(i));FileOutputStream(f).use{require(b.compress(Bitmap.CompressFormat.PNG,100,it))};b.recycle();paths+=f.absolutePath}else if(paths.isNotEmpty())paths+=paths.last();onProgress(i+1,count)};r.release();return Result(width,height,fps,paths.size,paths,durationUs)}
 private fun extractFps(context:Context,uri:Uri):Int=try{val e=MediaExtractor();e.setDataSource(context,uri,null);var f=24f;for(i in 0 until e.trackCount){val m=e.getTrackFormat(i);if(m.getString(MediaFormat.KEY_MIME)?.startsWith("video/")==true){if(m.containsKey(MediaFormat.KEY_FRAME_RATE))f=m.getInteger(MediaFormat.KEY_FRAME_RATE).toFloat();break}};e.release();f.roundToInt().coerceIn(1,240)}catch(_:Throwable){24}
}

object AnimationExportEngine {
 enum class Format{MP4,GIF,PNG_SEQUENCE}
 data class Settings(val width:Int,val height:Int,val fps:Int,val startFrame:Int=0,val endFrame:Int=0,val bitrate:Int=8_000_000)
 fun export(context:Context,output:Uri,format:Format,settings:Settings,render:(Int)->Bitmap){require(settings.width>0&&settings.height>0&&settings.fps in 1..240&&settings.endFrame>=settings.startFrame);when(format){Format.PNG_SEQUENCE->exportSequence(context,output,settings,render);Format.GIF->exportGif(context,output,settings,render);Format.MP4->exportMp4(context,output,settings,render)}}
 private fun exportSequence(context:Context,output:Uri,s:Settings,render:(Int)->Bitmap){val dir=File(context.cacheDir,"export_${System.currentTimeMillis()}").apply{mkdirs()};try{for(f in s.startFrame..s.endFrame){val b=render(f);FileOutputStream(File(dir,"frame_%06d.png".format(f))).use{require(b.compress(Bitmap.CompressFormat.PNG,100,it))};b.recycle()};context.contentResolver.openOutputStream(output)?.use{os->ZipOutputStream(os).use{z->dir.listFiles()?.sortedBy{it.name}?.forEach{file->z.putNextEntry(ZipEntry(file.name));file.inputStream().use{it.copyTo(z)};z.closeEntry()}}}?:error("Cannot open output")}finally{dir.deleteRecursively()}}
 private fun exportGif(context:Context,output:Uri,s:Settings,render:(Int)->Bitmap){context.contentResolver.openOutputStream(output)?.use{os->SimpleGifWriter(os,s.width,s.height,s.fps).use{g->for(f in s.startFrame..s.endFrame){val b=render(f);g.addFrame(b);b.recycle()};g.finish()}}?:error("Cannot open output")}
 private fun exportMp4(context:Context,output:Uri,s:Settings,render:(Int)->Bitmap){val fmt=MediaFormat.createVideoFormat("video/avc",s.width,s.height).apply{setInteger(MediaFormat.KEY_COLOR_FORMAT,MediaCodecInfo.CodecCapabilities.COLOR_FormatSurface);setInteger(MediaFormat.KEY_BIT_RATE,s.bitrate.coerceAtLeast(100_000));setInteger(MediaFormat.KEY_FRAME_RATE,s.fps);setInteger(MediaFormat.KEY_I_FRAME_INTERVAL,1)};val enc=MediaCodec.createEncoderByType("video/avc");enc.configure(fmt,null,null,MediaCodec.CONFIGURE_FLAG_ENCODE);val surface=enc.createInputSurface();enc.start();val fd=context.contentResolver.openFileDescriptor(output,"w")?:error("Cannot open output");val mux=android.media.MediaMuxer(fd.fileDescriptor,android.media.MediaMuxer.OutputFormat.MUXER_OUTPUT_MPEG_4);var track=-1;var started=false;val info=MediaCodec.BufferInfo();fun drain(wait:Boolean){while(true){val ix=enc.dequeueOutputBuffer(info,if(wait)10_000L else 0L);when{ix==MediaCodec.INFO_OUTPUT_FORMAT_CHANGED->{if(!started){track=mux.addTrack(enc.outputFormat);mux.start();started=true}};ix>=0->{val d=enc.getOutputBuffer(ix);if(d!=null&&info.size>0&&started){d.position(info.offset);d.limit(info.offset+info.size);mux.writeSampleData(track,d,info)};enc.releaseOutputBuffer(ix,false);if((info.flags and MediaCodec.BUFFER_FLAG_END_OF_STREAM)!=0)return};ix==MediaCodec.INFO_TRY_AGAIN_LATER->return}}};try{for(f in s.startFrame..s.endFrame){val b=render(f);val canvas=surface.lockCanvas(null);canvas.drawColor(Color.WHITE);canvas.drawBitmap(b,null,android.graphics.Rect(0,0,s.width,s.height),null);surface.unlockCanvasAndPost(canvas);b.recycle();drain(false)};enc.signalEndOfInputStream();drain(true)}finally{runCatching{surface.release()};runCatching{enc.stop()};enc.release();if(started)runCatching{mux.stop()};mux.release();fd.close()}}
}

private class SimpleGifWriter(private val out:java.io.OutputStream,private val w:Int,private val h:Int,private val fps:Int):java.io.Closeable{private var started=false;fun addFrame(src:Bitmap){if(!started){out.write("GIF89a".toByteArray());le16(w);le16(h);out.write(0xF7);out.write(0);out.write(0);for(i in 0 until 256){out.write(i and 0xE0);out.write((i and 0x1C) shl 3);out.write((i and 3) shl 6)};started=true};val b=Bitmap.createScaledBitmap(src,w,h,true);val p=IntArray(w*h);b.getPixels(p,0,w,0,0,w,h);b.recycle();out.write(byteArrayOf(0x21,0xF9.toByte(),4,0));le16((100/fps).coerceAtLeast(1));out.write(0);out.write(0);out.write(0x2C);le16(0);le16(0);le16(w);le16(h);out.write(0);writeLzw(p)};private fun writeLzw(p:IntArray){val indexed=ByteArray(p.size){i->val c=p[i];(((c ushr 16) and 0xE0) or (((c ushr 8) and 0xE0) ushr 3) or ((c and 0xC0) ushr 6)).toByte()};val clear=256;val eof=257;val codes=java.io.ByteArrayOutputStream();var acc=0;var bits=0;fun put(v:Int){acc=acc or(v shl bits);bits+=9;while(bits>=8){codes.write(acc and 255);acc=acc ushr 8;bits-=8}};put(clear);for(v in indexed){put(v.toInt() and 255);put(clear)};put(eof);if(bits>0)codes.write(acc and 255);val a=codes.toByteArray();out.write(8);var o=0;while(o<a.size){val n=minOf(255,a.size-o);out.write(n);out.write(a,o,n);o+=n};out.write(0)};private fun le16(v:Int){out.write(v and 255);out.write((v ushr 8) and 255)};fun finish(){if(started)out.write(0x3B);out.flush()};override fun close(){finish()}}
