package com.animame.editor

import android.app.Activity
import android.content.Context
import android.graphics.*
import android.net.Uri
import android.view.MotionEvent
import android.view.View
import kotlin.math.*

open class AnimationEditorViewV5(context:Context):View(context){
    private enum class Mode{HOME,EDITOR};private enum class Panel{OPTIONS,BRUSHES,LAYERS,TIMELINE,CAMERA,RULERS};private enum class Tool{BRUSH,PENCIL,ERASER,LASSO,FILL,PAN,TRANSFORM,LINE,RECTANGLE,ELLIPSE}
    private var mode=Mode.HOME;private var panel:Panel?=Panel.OPTIONS;private var dialog=false;private var menu=false;private var tool=Tool.BRUSH
    private var project:AnimationProject?=null;private var document=AnimationDocument();private var projectName="Untitled";private var fps=24;private var cw=1280;private var ch=720;private var margin=0;private var selectedLayerId=document.activeLayer.id
    private var selectedBrush=BrushCatalog.presets.first();private var brushSettings=selectedBrush.defaults.copy();private var brushSize=brushSettings.size;private var opacity=brushSettings.opacity;private var stabilizer=20f;private var realTimeStabilizer=true;private var antiAlias=true;private var ruler=0;private var symmetry=6
    private var playing=false;private var lastPlayTime=0L;private var frameAccumulator=0f;private val viewport=CanvasViewport();private val settings get()=EditorSettingsStore.current;private val history=EditorHistory(120);private val lowLatency=LowLatencyStabilizer()
    private var cameraX=0f;private var cameraY=0f;private var cameraScale=1f;private var cameraRotation=0f;private val samples=mutableListOf<Stabilizer.Sample>();private var current:Path?=null;private var lastPoint:PointF?=null;private var lastTime=0L;private val lasso=mutableListOf<PointF>();private val selectedStrokeIds=mutableSetOf<String>();private var gestureStart:PointF?=null;private val ui=Paint(Paint.ANTI_ALIAS_FLAG);private val bitmapCache=HashMap<String,Bitmap>()
    private var exportFormat:AnimationExportEngine.Format?=null
    init{setLayerType(View.LAYER_TYPE_SOFTWARE,null)}
    override fun onDraw(c:Canvas){if(mode==Mode.HOME)drawHome(c)else drawEditor(c);if(dialog)drawDialog(c);if(menu)drawMenu(c);if(playing){val now=System.currentTimeMillis();if(lastPlayTime==0L)lastPlayTime=now;frameAccumulator+=(now-lastPlayTime)/1000f*document.fps;lastPlayTime=now;while(frameAccumulator>=1f){document.currentFrame++;frameAccumulator-=1f;if(document.currentFrame>document.playbackEnd)document.currentFrame=document.playbackStart};postInvalidateDelayed(16)}}
    private fun bg(c:Canvas){ui.style=Paint.Style.FILL;ui.color=Color.rgb(16,17,19);c.drawRect(0f,0f,width.toFloat(),height.toFloat(),ui)}
    private fun drawHome(c:Canvas){bg(c);ui.color=Color.rgb(27,29,32);c.drawRect(0f,0f,width.toFloat(),54f,ui);text(c,"ANIMA-ME",22f,35f,Color.WHITE,18f);text(c,"Sort by date",width-115f,35f,Color.LTGRAY,10f);if(ProjectStore.projects.isEmpty())text(c,"No projects",width/2f-35f,height/2f,Color.LTGRAY,14f)else{var y=80f;ProjectStore.projects.forEach{p->ui.color=Color.rgb(36,39,43);c.drawRoundRect(24f,y,300f,y+150f,8f,8f,ui);text(c,p.name,40f,y+122f,Color.WHITE,12f);text(c,"${p.fps} fps   ${p.cameraWidth} x ${p.cameraHeight}",40f,y+141f,Color.GRAY,9f);y+=170f}};ui.color=Color.rgb(52,55,60);c.drawRoundRect(width-190f,height-76f,width-24f,height-26f,10f,10f,ui);text(c,"New project",width-154f,height-45f,Color.WHITE,12f)}
    private fun drawEditor(c:Canvas){bg(c);val w=width.toFloat();val h=height.toFloat();ui.color=Color.rgb(27,29,32);c.drawRect(0f,0f,w,50f,ui);text(c,"☰",18f,34f,Color.WHITE,24f);text(c,"ANIMA-ME",52f,32f,Color.WHITE,15f);text(c,project?.name?:"Untitled",150f,32f,Color.LTGRAY,12f);text(c,"${document.fps} FPS",w-116f,32f,Color.LTGRAY,12f);val r=canvasRect();ui.color=Color.WHITE;c.drawRect(r,ui);c.save();c.clipRect(r);c.concat(editorMatrix(r));drawOnion(c);drawCurrentFrame(c);if(current!=null)drawPreviewStroke(c);c.restore();drawRuler(c,r);drawLasso(c);tabs(c);rail(c);if(panel!=null)drawPanel(c,w-300f,h);timeline(c,h)}
    private fun drawCurrentFrame(c:Canvas){document.layers.asReversed().filter{it.visible}.forEach{layer->layer.frameAt(document.currentFrame)?.let{f->drawRaster(c,f);f.strokes.forEach{s->drawStroke(c,s)}}}}
    private fun drawRaster(c:Canvas,f:DrawingFrame){val path=f.rasterPath?:return;val b=bitmapCache.getOrPut(path){BitmapFactory.decodeFile(path)?:return};c.drawBitmap(b,null,RectF(0f,0f,document.width.toFloat(),document.height.toFloat()),null)}
    private fun drawOnion(c:Canvas){if(!document.onion.enabled)return;val layer=document.layers.firstOrNull{it.id==selectedLayerId}?:return;val a=(document.onion.opacity*2.55f).roundToInt().coerceIn(0,255);layer.previousFrames(document.currentFrame,document.onion.previousCount).forEach{(_,f)->f.strokes.forEach{s->drawStroke(c,s,if(document.onion.tintPrevious)Color.argb(a,80,150,255)else null)}};layer.nextFrames(document.currentFrame,document.onion.nextCount).forEach{(_,f)->f.strokes.forEach{s->drawStroke(c,s,if(document.onion.tintNext)Color.argb(a,255,110,110)else null)}}}
    private fun drawStroke(c:Canvas,s:StrokeData,tint:Int?=null){if(s.samples.isEmpty())return;val bs=s.brushSettings.copy(size=s.size,opacity=s.opacity).normalized();val list=s.samples;val total=strokeLength(list);val p=Paint(Paint.ANTI_ALIAS_FLAG).apply{style=Paint.Style.STROKE;strokeCap=Paint.Cap.ROUND;strokeJoin=Paint.Join.ROUND;isAntiAlias=bs.antialias&&antiAlias;color=tint?:s.color};if(bs.eraser&&tint==null)p.xfermode=PorterDuffXfermode(PorterDuff.Mode.DST_OUT);if(list.size==1){p.style=Paint.Style.FILL;p.alpha=(bs.opacityFor(list[0].pressure,list[0].tilt,0f,total)*255).roundToInt().coerceIn(0,255);c.drawCircle(list[0].x,list[0].y,bs.radiusFor(list[0].pressure,list[0].tilt)/2,p);return};var dist=0f;for(i in 1 until list.size){val a=list[i-1];val b=list[i];val d=hypot(b.x-a.x,b.y-a.y);val pr=((a.pressure+b.pressure)/2).coerceIn(.05f,1.5f);val width=bs.radiusFor(pr,(a.tilt+b.tilt)/2);p.strokeWidth=width;p.alpha=(bs.opacityFor(pr,(a.tilt+b.tilt)/2,dist,total)*255).roundToInt().coerceIn(0,255);c.drawLine(a.x,a.y,b.x,b.y,p);dist+=d};p.xfermode=null;if(selectedStrokeIds.contains(s.id)&&tint==null){val q=Paint(Paint.ANTI_ALIAS_FLAG).apply{style=Paint.Style.STROKE;color=Color.CYAN;strokeWidth=2f;pathEffect=DashPathEffect(floatArrayOf(5f,5f),0f)};val path=Path().apply{moveTo(list[0].x,list[0].y);list.drop(1).forEach{lineTo(it.x,it.y)}};c.drawPath(path,q)}}
    private fun drawPreviewStroke(c:Canvas){if(samples.isEmpty())return;drawStroke(c,StrokeData(brushId=selectedBrush.id,color=Color.BLACK,size=brushSize,opacity=opacity,brushSettings=brushSettings.copy(size=brushSize,opacity=opacity,eraser=tool==Tool.ERASER),samples=samples.map{StrokeSample(it.point.x,it.point.y,it.pressure,it.timeMs,it.tilt)}.toMutableList()))}
    private fun drawLasso(c:Canvas){if(lasso.size<2)return;val p=Paint(Paint.ANTI_ALIAS_FLAG).apply{style=Paint.Style.STROKE;color=Color.YELLOW;strokeWidth=2f;pathEffect=DashPathEffect(floatArrayOf(8f,6f),0f)};val q=Path().apply{moveTo(lasso[0].x,lasso[0].y);lasso.drop(1).forEach{lineTo(it.x,it.y)};if(tool!=Tool.LASSO)close()};c.drawPath(q,p)}
    private fun tabs(c:Canvas){listOf("OPTIONS","BRUSHES","LAYERS","TIMELINE","CAMERA","RULERS").forEachIndexed{i,n->{val x=190f+i*78f;ui.color=if(panel==Panel.values()[i])Color.rgb(68,73,81)else Color.rgb(43,46,50);c.drawRoundRect(x,9f,x+74f,41f,7f,7f,ui);text(c,n,x+7f,29f,Color.WHITE,8f)}}}
    private fun rail(c:Canvas){ui.color=Color.rgb(31,33,36);c.drawRect(0f,50f,62f,height-112f,ui);val names=listOf("BR","PE","ER","LA","FI","PI","MV","TR","LN","RE","EL");names.forEachIndexed{i,n->{if(Tool.values().getOrNull(i)==tool){ui.color=Color.rgb(70,75,84);c.drawRoundRect(4f,57f+i*41f,58f,92f+i*41f,6f,6f,ui)};text(c,n,19f,78f+i*41f,Color.WHITE,9f)}}}
    private fun drawPanel(c:Canvas,x:Float,h:Float){ui.color=Color.rgb(29,31,34);c.drawRect(x,50f,width.toFloat(),h-112f,ui);text(c,when(panel){Panel.OPTIONS->"TOOL OPTIONS";Panel.BRUSHES->"BRUSH LIBRARY";Panel.LAYERS->"LAYERS";Panel.TIMELINE->"TIMELINE";Panel.CAMERA->"CAMERA / TRANSFORM";Panel.RULERS->"RULERS";null->""},x+14f,78f,Color.WHITE,13f);when(panel){Panel.OPTIONS->options(c,x+14f);Panel.BRUSHES->brushes(c,x+14f);Panel.LAYERS->layers(c,x+14f);Panel.TIMELINE->timelinePanel(c,x+14f);Panel.CAMERA->camera(c,x+14f);Panel.RULERS->rulers(c,x+14f);null->Unit}}
    private fun options(c:Canvas,x:Float){text(c,"TOOL  ${tool.name}",x,106f,Color.WHITE,12f);text(c,"BRUSH  ${selectedBrush.name}",x,126f,Color.WHITE,11f);text(c,"SIZE  ${brushSize.roundToInt()} px",x,148f,Color.LTGRAY,10f);text(c,"OPACITY  ${(opacity*100).roundToInt()}%",x,170f,Color.LTGRAY,10f);text(c,"HARDNESS  ${(brushSettings.hardness*100).roundToInt()}%",x,192f,Color.LTGRAY,10f);text(c,"FEATHER  ${(brushSettings.feather*100).roundToInt()}%",x,212f,Color.LTGRAY,10f);text(c,"FLOW  ${(brushSettings.flow*100).roundToInt()}%",x,232f,Color.LTGRAY,10f);text(c,"SPACING  ${(brushSettings.spacing*100).roundToInt()}%",x,252f,Color.LTGRAY,10f);text(c,"PRESSURE SIZE  ${(brushSettings.pressureSize*100).roundToInt()}%",x,272f,Color.LTGRAY,10f);text(c,"PRESSURE OPACITY  ${(brushSettings.pressureOpacity*100).roundToInt()}%",x,292f,Color.LTGRAY,10f);text(c,"TILT SIZE  ${(brushSettings.tiltSize*100).roundToInt()}%",x,312f,Color.LTGRAY,10f);text(c,"SMOOTHING  ${stabilizer.roundToInt()}%",x,334f,Color.LTGRAY,10f);text(c,"STABILIZER  ${if(realTimeStabilizer)"REAL TIME" else "AFTER"}",x,356f,Color.LTGRAY,10f);text(c,"ANTI-ALIAS  ${if(antiAlias)"ON" else "OFF"}",x,378f,Color.LTGRAY,10f)}
    private fun brushes(c:Canvas,x:Float){var y=108f;BrushCatalog.families.forEach{f->if(y<height-135){text(c,f,x,y,Color.WHITE,10f);y+=18f;BrushCatalog.presets.filter{it.family==f}.forEach{p->if(y<height-135){text(c,if(p.id==selectedBrush.id)"• ${p.name}" else "  ${p.name}",x+6f,y,if(p.id==selectedBrush.id)Color.WHITE else Color.GRAY,9f);y+=16f}};y+=4f}}}
    private fun layers(c:Canvas,x:Float){text(c,"+ NEW LAYER",x,108f,Color.WHITE,10f);var y=138f;document.layers.forEach{l->text(c,if(l.id==selectedLayerId)"• ${l.name}" else "  ${l.name}",x,y,Color.LTGRAY,10f);text(c,"${if(l.visible)"VISIBLE" else "HIDDEN"}  ${if(l.locked)"LOCKED" else "UNLOCKED"}",x+115f,y,Color.GRAY,8f);y+=30f}}
    private fun timelinePanel(c:Canvas,x:Float){text(c,"CURRENT FRAME  ${document.currentFrame+1} / ${document.duration}",x,108f,Color.WHITE,10f);text(c,"ONION SKIN   ${if(document.onion.enabled)"ON" else "OFF"}",x,136f,Color.LTGRAY,10f);text(c,"PREVIOUS ${document.onion.previousCount}   NEXT ${document.onion.nextCount}",x,164f,Color.LTGRAY,10f)}
    private fun camera(c:Canvas,x:Float){text(c,"POSITION  ${cameraX.roundToInt()}, ${cameraY.roundToInt()}",x,108f,Color.LTGRAY,10f);text(c,"SCALE  ${(cameraScale*100).roundToInt()}%",x,136f,Color.LTGRAY,10f);text(c,"ROTATION  ${cameraRotation.roundToInt()}°",x,164f,Color.LTGRAY,10f);text(c,"RESET CAMERA",x,220f,Color.WHITE,10f)}
    private fun rulers(c:Canvas,x:Float){listOf("STRAIGHT RULER","CIRCULAR RULER","ELLIPSE RULER","RADIAL RULER","MIRROR RULER","KALEIDOSCOPE RULER","ROTATION RULER","ARRAY RULER","PERSPECTIVE ARRAY RULER").forEachIndexed{i,s->text(c,if(ruler==i+1)"• $s" else "  $s",x,108f+i*24f,if(ruler==i+1)Color.WHITE else Color.LTGRAY,9f)}}
    private fun drawRuler(c:Canvas,r:RectF){if(ruler==0)return;ui.style=Paint.Style.STROKE;ui.color=Color.rgb(105,140,175);ui.strokeWidth=1f;when(ruler){1->c.drawLine(r.left,r.centerY(),r.right,r.centerY(),ui);2->c.drawCircle(r.centerX(),r.centerY(),min(r.width(),r.height())*.32f,ui);3->c.drawOval(r.centerX()-r.width()*.3f,r.centerY()-r.height()*.2f,r.centerX()+r.width()*.3f,r.centerY()+r.height()*.2f,ui);4->repeat(24){i->val a=i*PI/12;c.drawLine(r.centerX(),r.centerY(),r.centerX()+cos(a).toFloat()*r.width(),r.centerY()+sin(a).toFloat()*r.height(),ui)};5->c.drawLine(r.centerX(),r.top,r.centerX(),r.bottom,ui);6,7->repeat(symmetry){i->c.save();c.rotate(i*360f/symmetry,r.centerX(),r.centerY());c.drawLine(r.centerX(),r.centerY(),r.right,r.centerY(),ui);c.restore()};8,9->repeat(5){i->val dx=i*r.width()*.12f;c.drawRect(r.left+dx,r.top+dx*.4f,r.right-dx,r.bottom-dx*.4f,ui)}}}
    private fun timeline(c:Canvas,h:Float){ui.color=Color.rgb(25,27,30);c.drawRect(0f,h-112f,width.toFloat(),h,ui);text(c,"◀",74f,h-76f,Color.WHITE,18f);text(c,"▶",108f,h-76f,Color.WHITE,18f);text(c,"▶▶",142f,h-76f,Color.WHITE,14f);text(c,"FRAME  ${document.currentFrame+1}",200f,h-78f,Color.WHITE,11f);text(c,"UNDO",320f,h-78f,Color.LTGRAY,10f);text(c,"REDO",365f,h-78f,Color.LTGRAY,10f);text(c,"ONION",415f,h-78f,Color.LTGRAY,10f);text(c,"+ FRAME",480f,h-78f,Color.LTGRAY,10f);text(c,"- FRAME",540f,h-78f,Color.LTGRAY,10f);text(c,"PLAY",600f,h-78f,Color.WHITE,11f)}
    private fun drawDialog(c:Canvas){ui.color=Color.argb(180,0,0,0);c.drawRect(0f,0f,width.toFloat(),height.toFloat(),ui);ui.color=Color.rgb(37,39,43);c.drawRoundRect(width/2f-230f,90f,width/2f+230f,430f,12f,12f,ui);text(c,"NEW PROJECT",width/2f-200f,128f,Color.WHITE,18f);text(c,"Name",width/2f-200f,170f,Color.GRAY,10f);text(c,projectName,width/2f-200f,195f,Color.WHITE,13f);text(c,"FPS",width/2f-200f,235f,Color.GRAY,10f);text(c,"$fps",width/2f-200f,258f,Color.WHITE,13f);text(c,"Camera",width/2f-200f,298f,Color.GRAY,10f);text(c,"$cw x $ch",width/2f-200f,322f,Color.WHITE,13f);text(c,"Margins  $margin x $margin",width/2f-200f,350f,Color.GRAY,10f);text(c,"CANCEL",width/2f+60f,405f,Color.LTGRAY,11f);text(c,"OKAY",width/2f+145f,405f,Color.WHITE,11f)}
    private fun drawMenu(c:Canvas){ui.color=Color.argb(210,0,0,0);c.drawRect(0f,0f,width.toFloat(),height.toFloat(),ui);ui.color=Color.rgb(30,32,35);c.drawRect(0f,0f,360f,height.toFloat(),ui);listOf("CLOSE PROJECT","EXPORT VIDEO","IMPORT AUDIO","IMPORT IMAGE(S)","IMPORT VIDEO","IMPORT PROJECT","CHANGE FRAMERATE","RESIZE / CROP / EXPAND").forEachIndexed{i,s->text(c,s,30f,70f+i*48f,Color.WHITE,12f)}}
    private fun text(c:Canvas,s:String,x:Float,y:Float,color:Int,size:Float){ui.style=Paint.Style.FILL;ui.color=color;ui.textSize=size;c.drawText(s,x,y,ui)}
    private fun canvasRect():RectF{val left=74f;val top=64f;val right=width-324f;val bottom=height-126f;return RectF(left,top,right,bottom)}
    private fun editorMatrix(r:RectF):Matrix{val m=Matrix();m.postTranslate(r.centerX()+cameraX,r.centerY()+cameraY);m.postScale(cameraScale,cameraScale);m.postRotate(cameraRotation);m.postTranslate(-document.width/2f,-document.height/2f);return m}
    private fun strokeLength(s:List<StrokeSample>):Float{var d=0f;for(i in 1 until s.size)d+=hypot(s[i].x-s[i-1].x,s[i].y-s[i-1].y);return d.coerceAtLeast(.001f)}
    override fun onTouchEvent(e:MotionEvent):Boolean{if(e.pointerCount>=2)return false;when(e.actionMasked){MotionEvent.ACTION_DOWN->{val p=toCanvas(e.x,e.y);gestureStart=p;when{dialog->return dialogTouch(e.x,e.y);menu->return menuTouch(e.x,e.y);mode==Mode.HOME->{if(e.x>width-210&&e.y>height-100){dialog=true;invalidate();return true};return true};panel==Panel.BRUSHES&&e.x>width-300->{selectBrushAt(e.x,e.y);return true};tool==Tool.BRUSH||tool==Tool.PENCIL||tool==Tool.ERASER->{samples.clear();samples+=Stabilizer.Sample(p);invalidate();return true};tool==Tool.LASSO->{lasso.clear();lasso+=p;invalidate();return true};tool==Tool.PAN->{return true}}};MotionEvent.ACTION_MOVE->{val p=toCanvas(e.x,e.y);when{tool==Tool.BRUSH||tool==Tool.PENCIL||tool==Tool.ERASER->{samples+=Stabilizer.Sample(p,1f,System.currentTimeMillis());current=Path().apply{moveTo(samples.first().point.x,samples.first().point.y);samples.drop(1).forEach{lineTo(it.point.x,it.point.y)}};invalidate();return true};tool==Tool.LASSO->{lasso+=p;invalidate();return true};tool==Tool.PAN->{val g=gestureStart?:p;cameraX+=p.x-g.x;cameraY+=p.y-g.y;gestureStart=p;invalidate();return true}}};MotionEvent.ACTION_UP->{val p=toCanvas(e.x,e.y);when{tool==Tool.BRUSH||tool==Tool.PENCIL||tool==Tool.ERASER->{if(samples.isNotEmpty()){val frame=document.activeLayer.ensureFrame(document.currentFrame);frame.strokes+=StrokeData(brushId=selectedBrush.id,color=Color.BLACK,size=brushSize,opacity=opacity,brushSettings=brushSettings.copy(size=brushSize,opacity=opacity,eraser=tool==Tool.ERASER),samples=samples.map{StrokeSample(it.point.x,it.point.y,it.pressure,it.timeMs,it.tilt)}.toMutableList())};samples.clear();current=null;invalidate();return true};tool==Tool.LASSO->{if(lasso.size>2)lasso+=lasso.first();invalidate();return true}}};return true}
    private fun toCanvas(x:Float,y:Float):PointF{val r=canvasRect();val inv=Matrix();editorMatrix(r).invert(inv);val p=floatArrayOf(x,y);inv.mapPoints(p);return PointF(p[0],p[1])}
    private fun selectBrushAt(x:Float,y:Float){var row=108f;BrushCatalog.families.forEach{f->row+=18f;BrushCatalog.presets.filter{it.family==f}.forEach{p->if(y>=row-13&&y<row+7){selectedBrush=p;brushSettings=p.defaults.copy();brushSize=brushSettings.size;opacity=brushSettings.opacity;invalidate();return};row+=16f};row+=4f}}
    private fun dialogTouch(x:Float,y:Float):Boolean{if(y>370&&x>width/2f+120){document=AnimationDocument(name=projectName,width=cw,height=ch,fps=fps);selectedLayerId=document.activeLayer.id;mode=Mode.EDITOR;dialog=false;invalidate();return true};if(y>370&&x>width/2f){dialog=false;invalidate();return true};return true}
    private fun menuTouch(x:Float,y:Float):Boolean{if(x>360){menu=false;invalidate();return true};return true}
    private fun drawMenuTouch():Unit{}
}