package com.animame.editor

import android.graphics.*
import kotlin.math.*

object BrushEngine {
    private val rng=java.util.Random()
    fun drawStroke(canvas:Canvas,stroke:StrokeData,color:Int,scale:Float=1f){
        val s=stroke.resolvedBrushSettings(); val pts=stroke.samples; if(pts.isEmpty())return
        if(pts.size==1){stamp(canvas,pts[0].x,pts[0].y,0f,s.size*scale,s,color);return}
        for(i in pts.indices){val p=pts[i];val prev=pts[max(0,i-1)];val dx=p.x-prev.x;val dy=p.y-prev.y;val dist=hypot(dx,dy);val angle=atan2(dy,dx);val pressure=s.pressureCurveSize.eval(p.pressure);val speed=(dist/max(1L,p.timeMs-prev.timeMs)).coerceIn(0f,4f);val size=(s.size*(1f+s.pressureSize*(pressure-.5f))*(1f-s.speedSize*speed*.12f)).coerceAtLeast(.1f)*scale;val op=(s.opacity*(1f+s.pressureOpacity*(s.pressureCurveOpacity.eval(p.pressure)-.5f))*(1f-s.speedOpacity*speed*.08f)).coerceIn(0f,1f);val paint=Paint(Paint.ANTI_ALIAS_FLAG or Paint.FILTER_BITMAP_FLAG).apply{alpha=(op*255).roundToInt();this.color=jitterColor(color,s)};val step=max(.5f,size*s.spacing);if(i==0||dist>=step||i==pts.lastIndex)stamp(canvas,p.x,p.y,angle,size,s,paint.color,paint)}
    }
    private fun stamp(c:Canvas,x:Float,y:Float,angle:Float,size:Float,s:BrushSettings,color:Int,paint0:Paint?=null){val p=paint0?:Paint(Paint.ANTI_ALIAS_FLAG).apply{this.color=color;alpha=(s.opacity*255).roundToInt()};val save=c.save();c.translate(x,y);c.rotate(Math.toDegrees((angle*s.rotationFollow+s.angle/57.29578f).toDouble()).toFloat());val count=when(s.algorithm){BrushAlgorithm.PARTICLE->max(1,(s.particleDensity*2).roundToInt());else->1};repeat(count){val ox=(rng.nextFloat()*2f-1f)*s.scatter*size;val oy=(rng.nextFloat()*2f-1f)*s.scatter*size;val ps=(size*(s.particleSize*(1f+(rng.nextFloat()-.5f)*s.jitterSize))).coerceAtLeast(.1f);drawPattern(c,ox,oy,ps,s,p)};c.restoreToCount(save)}
    private fun drawPattern(c:Canvas,x:Float,y:Float,size:Float,s:BrushSettings,p:Paint){val rx=size*.5f;val ry=rx/s.aspect;when(s.pattern){"square"->c.drawRect(x-rx,y-ry,x+rx,y+ry,p);"triangle"->{val q=Path();q.moveTo(x,y-ry);q.lineTo(x+rx,y+ry);q.lineTo(x-rx,y+ry);q.close();c.drawPath(q,p)};"diamond"->{val q=Path();q.moveTo(x,y-ry);q.lineTo(x+rx,y);q.lineTo(x,y+ry);q.lineTo(x-rx,y);q.close();c.drawPath(q,p)};"star"->{val q=Path();for(i in 0 until 10){val a=-PI/2+i*PI/5;val r=if(i%2==0)rx else rx*.42f;val px=x+cos(a)*r;val py=y+sin(a)*r;if(i==0)q.moveTo(px,py)else q.lineTo(px,py)};q.close();c.drawPath(q,p)};"heart"->{val q=Path();q.moveTo(x,y+ry);q.cubicTo(x-rx*1.4f,y,x-rx,y-ry,x-rx*.45f,y-ry*.55f);q.cubicTo(x,y-ry*1.15f,x,y-ry*1.15f,x+rx*.45f,y-ry*.55f);q.cubicTo(x+rx,y-ry,x+rx*1.4f,y,x,y+ry);q.close();c.drawPath(q,p)};"line"->c.drawRect(x-rx,y-ry*.15f,x+rx,y+ry*.15f,p);"dot"->c.drawCircle(x,y,rx*.7f,p);"leaf"->{val q=Path();q.moveTo(x-rx,y);q.quadTo(x,y-ry*1.4f,x+rx,y);q.quadTo(x,y+ry*1.4f,x-rx,y);q.close();c.drawPath(q,p)};"petal"->{val q=Path();q.moveTo(x,y);q.quadTo(x-rx,y-ry*1.6f,x,y-ry*2f);q.quadTo(x+rx,y-ry*1.6f,x,y);q.close();c.drawPath(q,p)};else->c.drawOval(x-rx,y-ry,x+rx,y+ry,p)};if(s.blur>0f){val bp=Paint(p);bp.maskFilter=BlurMaskFilter(size*s.blur*.8f,BlurMaskFilter.Blur.NORMAL);c.drawCircle(x,y,rx,bp)};if(s.texture>0f){val tp=Paint(p);tp.alpha=(p.alpha*s.texture*.45f).roundToInt();repeat(max(1,(size/5).roundToInt())){c.drawCircle(x+(rng.nextFloat()*2-1)*rx,y+(rng.nextFloat()*2-1)*ry,max(.3f,size*.035f),tp)}}}
    private fun jitterColor(color:Int,s:BrushSettings):Int{if(s.colorJitterHue==0f&&s.colorJitterSaturation==0f&&s.colorJitterBrightness==0f)return color;val hsv=FloatArray(3);Color.colorToHSV(color,hsv);hsv[0]=(hsv[0]+(rng.nextFloat()*2-1)*s.colorJitterHue*360+360)%360;hsv[1]=(hsv[1]+(rng.nextFloat()*2-1)*s.colorJitterSaturation).coerceIn(0f,1f);hsv[2]=(hsv[2]+(rng.nextFloat()*2-1)*s.colorJitterBrightness).coerceIn(0f,1f);return Color.HSVToColor(Color.alpha(color),hsv)}
}
