package com.animame.editor

enum class BrushAlgorithm { MONO, WATER, DOUBLE, COLOR, AIRBRUSH, PARTICLE, BLUR, ERASER, VECTOR }
enum class BrushCategory { INK, SKETCH, WATERCOLOUR, PAINT, MARKER, PASTEL, CHARCOAL, EFFECTS, LIGHT, PLANTS, MATERIALS, HAIR, COMIC, DIGITAL, POINTILLISM, STAMP, ERASER, VECTOR, OTHER }
data class CurvePoint(val x:Float,val y:Float)
data class PressureCurve(val points:List<CurvePoint> = listOf(CurvePoint(0f,0f),CurvePoint(.5f,.5f),CurvePoint(1f,1f))){fun eval(v:Float):Float{val x=v.coerceIn(0f,1f);val p=points.sortedBy{it.x};for(i in 0 until p.lastIndex)if(x<=p[i+1].x){val t=((x-p[i].x)/(p[i+1].x-p[i].x).coerceAtLeast(1e-5f));return p[i].y+(p[i+1].y-p[i].y)*t};return p.last().y}}
data class BrushSettings(val id:String,val name:String,val category:BrushCategory,val algorithm:BrushAlgorithm,val size:Float=12f,val opacity:Float=1f,val minSize:Float=.05f,val maxSize:Float=1f,val fadeStart:Float=0f,val fadeEnd:Float=1f,val spacing:Float=.18f,val aspect:Float=1f,val angle:Float=0f,val rotationFollow:Float=1f,val jitterPosition:Float=0f,val jitterSize:Float=0f,val jitterOpacity:Float=0f,val jitterRotation:Float=0f,val scatter:Float=0f,val particleDensity:Float=1f,val particleSize:Float=1f,val blur:Float=0f,val texture:Float=0f,val textureScale:Float=1f,val wetness:Float=0f,val colorMix:Float=0f,val dragging:Float=0f,val pressureSize:Float=0f,val pressureOpacity:Float=0f,val speedSize:Float=0f,val speedOpacity:Float=0f,val pressureCurveSize:PressureCurve=PressureCurve(),val pressureCurveOpacity:PressureCurve=PressureCurve(),val blendMode:String="SRC_OVER",val invert:Boolean=false,val lockSizeOpacity:Boolean=false,val thinSpacing:Boolean=false,val antialias:Boolean=true,val pattern:String="circle",val colorJitterHue:Float=0f,val colorJitterSaturation:Float=0f,val colorJitterBrightness:Float=0f,val useCurrentColor:Boolean=true){fun normalized()=copy(size=size.coerceIn(.1f,512f),opacity=opacity.coerceIn(0f,1f),spacing=spacing.coerceIn(.01f,4f),aspect=aspect.coerceIn(.05f,8f),particleDensity=particleDensity.coerceIn(.05f,20f),particleSize=particleSize.coerceIn(.05f,8f),textureScale=textureScale.coerceIn(.05f,20f))}
object BrushDefaults{fun forPreset(id:String)=BrushCatalog.byId(id).settings}
object BrushCatalog{
 data class Preset(val id:String,val name:String,val settings:BrushSettings)
 private val names by lazy{BrushCatalog::class.java.getResourceAsStream("/brush_catalog.txt")!!.bufferedReader().readLines().filter{it.isNotBlank()}}
 val presets:List<Preset> by lazy{names.mapIndexed{i,n->Preset("animame.${i+1}",n,profile(i,n,"animame.${i+1}"))}}
 private val ids by lazy{presets.associateBy{it.id}}
 fun byId(id:String)=ids[id]?:presets.first()
 fun search(q:String)=if(q.isBlank())presets else presets.filter{it.name.contains(q,true)}
 fun byCategory(c:BrushCategory)=presets.filter{it.settings.category==c}
 private fun profile(i:Int,n:String,id:String):BrushSettings{
  val l=n.lowercase();val cat=when{l.contains("watercolor")||l.contains("gouache")->BrushCategory.WATERCOLOUR;l.contains("pencil")||l.contains("mechanical")||l.contains("sketch")||l.contains("crayon")||l.contains("pastel")||l.contains("charcoal")||l.contains("chalk")->BrushCategory.SKETCH;l.contains("ink")||l.contains("pen")||l.contains("calligraphy")||l.contains("ruling")||l.contains("fountain")||l.contains("ballpoint")->BrushCategory.INK;l.contains("marker")->BrushCategory.MARKER;l.contains("oil")||l.contains("acrylic")||l.contains("brush")||l.contains("paint")->BrushCategory.PAINT;l.contains("hair")||l.contains("braid")||l.contains("fur")->BrushCategory.HAIR;l.contains("grass")||l.contains("leaf")||l.contains("tree")||l.contains("flower")||l.contains("petal")||l.contains("rose")||l.contains("chrysanthemum")->BrushCategory.PLANTS;l.contains("glitter")||l.contains("neon")||l.contains("light")||l.contains("spark")||l.contains("flare")||l.contains("prism")||l.contains("sequin")->BrushCategory.LIGHT;l.contains("dot")||l.contains("pointill")||l.contains("moire")||l.contains("hatch")||l.contains("cross")||l.contains("grid")||l.contains("stripe")->BrushCategory.POINTILLISM;l.contains("eraser")->BrushCategory.ERASER;l.contains("vector")->BrushCategory.VECTOR;l.contains("airbrush")||l.contains("blur")||l.contains("sputter")||l.contains("splash")||l.contains("cloud")->BrushCategory.EFFECTS;l.contains("chain")||l.contains("stitch")||l.contains("lace")||l.contains("knitting")||l.contains("bead")||l.contains("hose")->BrushCategory.MATERIALS;l.contains("outline")->BrushCategory.COMIC;l.contains("cat footprint")||l.contains("dragonfly")||l.contains("gear")||l.contains("crown")||l.contains("star")||l.contains("heart")||l.contains("triangle")||l.contains("hexagon")||l.contains("pentagram")->BrushCategory.STAMP;else->BrushCategory.DIGITAL}
  val alg=when{cat==BrushCategory.WATERCOLOUR->BrushAlgorithm.WATER;cat==BrushCategory.ERASER->BrushAlgorithm.ERASER;cat==BrushCategory.LIGHT||cat==BrushCategory.POINTILLISM||cat==BrushCategory.MATERIALS||cat==BrushCategory.STAMP||l.contains("particle")->BrushAlgorithm.PARTICLE;l.contains("airbrush")->BrushAlgorithm.AIRBRUSH;l.contains("blur")||l.contains("blurring")->BrushAlgorithm.BLUR;l.contains("vector")->BrushAlgorithm.VECTOR;l.contains("shadow")->BrushAlgorithm.DOUBLE;l.contains("color")||l.contains("rainbow")||l.contains("neon")->BrushAlgorithm.COLOR;else->BrushAlgorithm.MONO}
  val r=((i*1103515245L+12345L) and 0x7fffffff).toFloat()/0x7fffffff.toFloat();val base=when(cat){BrushCategory.SKETCH->8f;BrushCategory.INK->10f;BrushCategory.WATERCOLOUR->22f;BrushCategory.PAINT->28f;BrushCategory.MARKER->18f;BrushCategory.HAIR->6f;else->12f}
  return BrushSettings(id,n,cat,alg,size=base*(.55f+r*1.35f),opacity=.92f,minSize=if(l.contains("pencil")||l.contains("pen")) .18f else .35f,maxSize=if(l.contains("marker")||l.contains("oil"))1.35f else 1f,fadeStart=if(l.contains("fade")||l.contains("bleed")) .15f else 0f,fadeEnd=if(l.contains("fade")||l.contains("bleed")) .92f else 1f,spacing=when(alg){BrushAlgorithm.PARTICLE->.45f;BrushAlgorithm.AIRBRUSH->.22f;else->.12f+r*.18f},aspect=if(l.contains("flat"))2.4f else if(l.contains("fan"))3.5f else 1f,angle=r*360f,rotationFollow=if(l.contains("angle")||l.contains("following"))1f else .15f,jitterPosition=if(l.contains("rough")||l.contains("sputter")||l.contains("particle")) .22f else 0f,jitterSize=if(l.contains("rough")||l.contains("fur")||l.contains("hair")) .22f else .05f,jitterOpacity=if(l.contains("glitter")||l.contains("particle")) .18f else .04f,jitterRotation=if(l.contains("particle")||l.contains("flower")||l.contains("leaf")) .65f else .05f,scatter=if(alg==BrushAlgorithm.PARTICLE).55f else if(l.contains("splash")||l.contains("sputter")) .35f else 0f,particleDensity=if(alg==BrushAlgorithm.PARTICLE)1.2f+r*2.5f else 1f,particleSize=if(alg==BrushAlgorithm.PARTICLE).25f+r*1.2f else 1f,blur=if(alg==BrushAlgorithm.BLUR||alg==BrushAlgorithm.AIRBRUSH).5f else if(l.contains("bleed")) .12f else 0f,texture=if(l.contains("texture")||l.contains("rough")||cat==BrushCategory.SKETCH).35f else if(cat==BrushCategory.WATERCOLOUR).18f else .04f,textureScale=.7f+r*2.2f,wetness=if(cat==BrushCategory.WATERCOLOUR).65f else 0f,colorMix=if(cat==BrushCategory.WATERCOLOUR).55f else 0f,dragging=if(cat==BrushCategory.WATERCOLOUR).22f else if(l.contains("oil")) .12f else 0f,pressureSize=.65f,pressureOpacity=.25f,speedSize=if(l.contains("speed")) .65f else .12f,speedOpacity=if(l.contains("speed")) .12f else .02f,blendMode=if(cat==BrushCategory.ERASER)"CLEAR" else "SRC_OVER",thinSpacing=l.contains("thin"),pattern=when{l.contains("triangle")->"triangle";l.contains("square")||l.contains("cube")->"square";l.contains("star")||l.contains("pentagram")->"star";l.contains("heart")->"heart";l.contains("diamond")->"diamond";l.contains("hexagon")||l.contains("sequin")->"hexagon";l.contains("petal")||l.contains("flower")->"petal";l.contains("leaf")||l.contains("grass")->"leaf";l.contains("line")||l.contains("stitch")->"line";l.contains("dot")||l.contains("point")->"dot";else->"circle"},colorJitterHue=if(l.contains("color")||l.contains("rainbow")||l.contains("neon")) .35f else 0f,colorJitterSaturation=if(l.contains("color")) .2f else 0f,colorJitterBrightness=if(l.contains("glitter")||l.contains("light")) .25f else 0f)
 }
}
