package com.animame.editor

/** Original Anima-me preset catalog. Names are reference labels; rendering is generated by our own engine. */
object BrushCatalog {
    private val names = """
Dip Pen (Soft)|Simple
Dip Pen (Hard)|Simple
Dip Pen (Bleed)|Ink
Felt Tip Pen (Soft)|Ink
Felt Tip Pen (Hard)|Ink
Digital Pen|Digital
Airbrush (Normal)|Airbrush
Airbrush (Triangle)|Airbrush
Airbrush (Trapezoid 20%)|Airbrush
Airbrush (Trapezoid 40%)|Airbrush
Airbrush (Trapezoid 60%)|Airbrush
Airbrush (Particle)|Airbrush
Airbrush (Particle L)|Airbrush
Pencil (#1)|Sketch
Pencil (#2)|Sketch
Pencil (Graphite)|Sketch
Watercolor (Real)|Watercolor
Watercolor (Point)|Watercolor
Watercolor (Bleed)|Watercolor
Oil (Rough)|Paint
Oil (Hair)|Paint
Oriental (Shan Shui)|Ink
Round Brush (Point)|Brushes
Round Brush (Normal)|Brushes
Round Brush (Curve)|Brushes
Round Brush (Angle)|Brushes
Round Brush (Fan)|Brushes
Round Brush (Real)|Brushes
Round Brush (Rough)|Brushes
Round Brush (Particle)|Brushes
Flat Brush (Point)|Brushes
Flat Brush (Normal)|Brushes
Flat Brush (Curve)|Brushes
Flat Brush (Angle)|Brushes
Flat Brush (Fan)|Brushes
Flat Brush (Real)|Brushes
Flat Brush (Line)|Brushes
Marker|Markers
Five Lines|Digital
Charcoal|Sketch
Soft Pastel|Pastel
Hard Pastel|Pastel
Crayon|Pastel
Chalk|Pastel
Net1|Effects
Net2|Effects
Net3|Effects
Net4|Effects
Circular Cross Hatching|Effects
Flash|Effects
Wedge|Effects
Pile|Effects
Speed|Effects
Splash|Effects
Circle (Edge)|Effects
Flare|Light
Light 4|Light
Light 6|Light
Light 8|Light
Heart|Stamps
Star|Stamps
Star (Round)|Stamps
Triangle|Stamps
Triangle (Noise)|Stamps
Pentagon|Stamps
Hexagon|Stamps
Blur Circle (In)|Effects
Blur Circle (Out)|Effects
Blur Pentagon (In)|Effects
Blur Pentagon (Out)|Effects
Eighth Note|Stamps
Doublet Note|Stamps
Snow1|Stamps
Snow2|Stamps
Petal|Plants
Petal (Outline)|Plants
Cherry Blossom|Plants
Cherry Blossom (Outline)|Plants
Chrysanthemum|Plants
Chrysanthemum (Outline)|Plants
Ume Blossom|Plants
Ume Blossom (Outline)|Plants
Balloon Flower|Plants
Balloon Flower (Outline)|Plants
Morning Glory|Plants
Morning Glory (Outline)|Plants
Peony|Plants
Peony (Outline)|Plants
Rose|Plants
Rose (Outline)|Plants
Leaf|Plants
Leaf (Outline)|Plants
Ginkgo|Plants
Ginkgo (Outline)|Plants
Maple|Plants
Maple (Outline)|Plants
Wood Sorrel|Plants
Wood Sorrel (Outline)|Plants
Clover|Plants
Clover (Outline)|Plants
Pen (Fade)|Ink
Chain 1|Chains
Lace|Materials
Feather|Materials
Swallowtail|Materials
Spider Net|Materials
Waterwheel|Materials
Waterwheel (Outline)|Materials
Gear Wheel1|Materials
Gear Wheel1 (Outline)|Materials
Gear Wheel2|Materials
Gear Wheel2 (Outline)|Materials
Pinwheel|Materials
Pinwheel (Outline)|Materials
Square|Stamps
Pentagram1|Stamps
Pentagram2|Stamps
Pentagram3|Stamps
Hexagram1|Stamps
Hexagram2|Stamps
Hexagram3|Stamps
Calligraphy|Ink
Light Diamond|Light
Light Diamond (Outline)|Light
Diamond (Real Top)|Stamps
Diamond (Real Side)|Stamps
Diamond (Icon)|Stamps
Queen Crown|Stamps
Queen Crown (Outline)|Stamps
King Crown|Stamps
King Crown (Outline)|Stamps
Drop|Stamps
Drop (Outline)|Stamps
Dragonfly|Stamps
Dragonfly (Outline)|Stamps
Grass (Fern)|Plants
Grass (Green foxtail)|Plants
Grass (Sedge)|Plants
Grass (Nutsedge)|Plants
Grass (Goosegrass)|Plants
Grass (Kentucky Bluegrass)|Plants
Grass (Luzula)|Plants
Watercolor (Mix)|Watercolor
Watercolor (Water)|Watercolor
Watercolor (Opaque)|Watercolor
Outline|Outlines
Light|Light
Flat Watercolor (Mix)|Watercolor
Flat Watercolor (Water)|Watercolor
Flat Watercolor (Opaque)|Watercolor
One Stroke Dragon|Stamps
Cat Footprint|Stamps
Cat Footprint (Outline)|Stamps
Cat Footprints|Stamps
Cat Footprints (Outline)|Stamps
Pasta 1|Materials
Pasta 2|Materials
Pasta 3|Materials
Pasta 4|Materials
Beads (Normal)|Materials
Beads (Thickness)|Materials
Hose|Materials
Rainbow|Effects
Sparkler|Effects
Flower Shower|Effects
Leaf Shower|Effects
Fur 1|Hair
Fur 2|Hair
Pencil (Rough)|Sketch
Blurring Brush 1|Effects
Blurring Brush 2|Effects
Blurring Brush 3|Effects
Blurring Brush 4|Effects
Blurring Brush 5|Effects
Blurring Marker 1|Markers
Blurring Marker 2|Markers
Love Pen|Ink
Ink Pen|Ink
Texture Pen|Digital
Hair|Hair
Glitter 1|Effects
Glitter 2|Effects
Glitter 3|Effects
Glitter 4|Effects
Glitter 5|Effects
Glitter 6|Effects
Bone|Materials
Moire 1|Effects
Moire 2|Effects
Hatching Mod 1|Effects
Hatching Mod 2|Effects
Pencil Mod (#1)|Sketch
Pencil Mod (#2)|Sketch
Pencil Mod (#3)|Sketch
Mechanical Pencil (#1)|Sketch
Mechanical Pencil (#2)|Sketch
Mechanical Pencil (#3)|Sketch
Colored Pencil|Sketch
Watercolor Pencil|Sketch
Ripple Marks|Effects
Dot|Effects
Grid Dot|Effects
Edge Dot|Effects
Round Dot|Effects
Soft Mapping Pen (Bleed)|Ink
Hard Mapping Pen (Smooth)|Ink
Soft Turnip Pen (Bleed)|Ink
Hard Turnip Pen (Smooth)|Ink
Soft School Pen (Bleed)|Ink
Hard School Pen (Smooth)|Ink
Soft Dip Pen (Bleed)|Ink
Hard Dip Pen (Smooth)|Ink
Soft Japanese Pen (Bleed)|Ink
Hard Japanese Pen (Smooth)|Ink
Soft Falcon Pen (Bleed)|Ink
Hard Falcon Pen (Smooth)|Ink
Technical Pen|Ink
Ruling Pen|Ink
Drawing Pen|Ink
Ballpoint Pen|Ink
Water-based Ballpoint Pen|Ink
Fountain Pen|Ink
Glass Pen|Ink
Uniform Eraser (Overlay)|Eraser
Uniform Eraser (Saturation)|Eraser
Soft Behind Pen (Bleed)|Ink
Hard Behind Pen (Smooth)|Ink
Outline (Fade)|Outlines
Color Outline (Thick)|Outlines
Color Outline (Middle)|Outlines
Color Outline (Thin)|Outlines
Shadow Text|Effects
Pointillism 1|Pointillism
Pointillism 2|Pointillism
Pointillism 3|Pointillism
Pointillism 4|Pointillism
Pointillism 5|Pointillism
Pointillism 6|Pointillism
Crayon Mod|Pastel
Alcohol Marker (Round)|Markers
Alcohol Marker (Flat)|Markers
Soft Pastel Mod|Pastel
Hard Pastel Mod|Pastel
Oil Pastel|Pastel
Pan Pastel|Pastel
Charcoal Mod|Sketch
Fade Watercolor (Mix)|Watercolor
Fade Watercolor (Water)|Watercolor
Fade Watercolor (Opaque)|Watercolor
Impressionism 1|Paint
Impressionism 2|Paint
Oil (Soft)|Paint
Oil (Hard)|Paint
Knitting|Materials
Knitting (Color Change)|Materials
Knitting (Gradation)|Materials
Glitter Heart|Effects
Sputtering 1|Effects
Sputtering 2|Effects
Gauze|Materials
Hair (Light)|Hair
Hair (Dark)|Hair
Blurring Outline|Outlines
Light (Pale)|Light
With Holes|Materials
With Holes (Outline)|Materials
Vertical Stripes|Effects
Horizontal Stripes|Effects
Dot Pen|Ink
Orthogonal Cross|Effects
Diagonal Cross|Effects
Grid|Effects
Houndstooth|Effects
Blurring Square|Effects
Only Outline (Part)|Outlines
Only Outline (Connect)|Outlines
Tube Pen|Materials
Diagonal Shadow Pen|Ink
Braid (White)|Hair
Braid (Pale)|Hair
Braid (Light)|Hair
Braid (Vivid)|Hair
Braid (Dark)|Hair
Stitch (Thick)|Materials
Stitch (Middle)|Materials
Stitch (Thin)|Materials
Stitch (Frame)|Materials
Stitch (Line)|Materials
Clouds (Real)|Effects
Clouds (Cotton)|Effects
Clouds (Scale)|Effects
Fluffy Watercolor (Mix)|Watercolor
Fluffy Watercolor (Water)|Watercolor
Fluffy Watercolor (Opaque)|Watercolor
Transparent Watercolor (Mix)|Watercolor
Transparent Watercolor (Water)|Watercolor
Transparent Watercolor (Opaque)|Watercolor
Gouache (Mix)|Paint
Gouache (Water)|Paint
Gouache (Opaque)|Paint
Acrylic (Mix)|Paint
Acrylic (Water)|Paint
Acrylic (Opaque)|Paint
Dashed Line|Effects
Dotted Line (Square)|Effects
Dotted Line (Round)|Effects
Watercolor (Edge)|Watercolor
Neon 1|Light
Neon 2|Light
Glitter Dot|Effects
Cube Pen|Digital
Fastener|Materials
Genius Pen|Digital
Stylish Marker|Markers
Rough Layout Pen (Blurring)|Sketch
Frizzily Pen|Ink
Glitter Pen|Effects
Scribble Brush|Brushes
Scribble Pen|Ink
Fashionable Pen|Ink
Stylish Pen|Ink
Stylish Brush|Brushes
Prism Ring|Effects
Prism Piece|Effects
Prism Flash|Effects
Japanese Calligraphy (Blurring)|Ink
Japanese Calligraphy|Ink
Sequin Pen|Effects
Sequin Pen (Hexagon)|Effects
Sequin Pen (Star)|Effects
Sequin Pen (Heart)|Effects
Hair Gloss 1|Hair
Hair Gloss 2|Hair
Three Strand Braid|Hair
Three Strand Braid (Outline)|Hair
Four Strand Braid|Hair
Four Strand Braid (Outline)|Hair
Grass (Fern, Color)|Plants
Grass (Green foxtail, Color)|Plants
Grass (Sedge, Color)|Plants
Grass (Nutsedge, Color)|Plants
Grass (Goosegrass, Color)|Plants
Grass (Kentucky Bluegrass, Color)|Plants
Grass (Luzula, Color)|Plants
Leaves 1|Plants
Leaves 2|Plants
Leaf (Color)|Plants
Tree 1|Plants
Tree 2|Plants
Trunk 1|Plants
Chain 2 (Color)|Chains
Chain 2 (Outline, Color)|Chains
Chain 3 (Color)|Chains
Chain 3 (Outline, Color)|Chains
Chain 4 (Color)|Chains
Chain 4 (Outline, Color)|Chains
Chain 5 (Color)|Chains
Chain 5 (Outline, Color)|Chains
Chain 6 (Color)|Chains
Chain 6 (Outline, Color)|Chains
Chain 7 (Color)|Chains
Chain 7 (Outline, Color)|Chains
Chain 8 (Color)|Chains
Chain 8 (Outline, Color)|Chains
Hard (Edge)|Ink
Watercolor (Edge 2)|Watercolor
Watercolor (Edge 3)|Watercolor
Watercolor (Mix 2)|Watercolor
Watercolor (Opaque 2)|Watercolor
Flat Watercolor (Mix 2)|Watercolor
Flat Watercolor (Opaque 2)|Watercolor
Fade Watercolor (Opaque 2)|Watercolor
Fluffy Watercolor (Mix 2)|Watercolor
Fluffy Watercolor (Opaque 2)|Watercolor
Transparent Watercolor (Mix 2)|Watercolor
Transparent Watercolor (Opaque 2)|Watercolor
Gouache (Mix 2)|Paint
Gouache (Opaque 2)|Paint
Acrylic (Mix 2)|Paint
Acrylic (Opaque 2)|Paint
Fade Watercolor (Mix 2)|Watercolor
Color Changing 1|Digital
Color Changing 2|Digital
Coarse Pencil|Sketch
Coarse Pencil (Light)|Sketch
Bleed Watercolor|Watercolor
Bleed Watercolor (Dark)|Watercolor
Vector Dip Pen|Vector
Vector Felt Tip Pen|Vector
""".trimIndent().lines().filter { it.isNotBlank() }
        .mapIndexed { i, line -> val p=line.split('|', limit=2); Preset("canvas_${i+1}", p[0], p[1]) }

    data class Preset(val id:String,val name:String,val category:String)
    fun all(): List<Preset> = names
    fun categories(): List<String> = names.map { it.category }.distinct()
    fun settings(id:String): BrushSettings { val p=names.firstOrNull{it.id==id} ?: return BrushDefaults.forPreset(id); return BrushDefaults.forPreset(id).copy(id=p.id,name=p.name,category=p.category) }
}
