package com.animame.editor

import org.json.JSONArray
import org.json.JSONObject
import java.util.UUID

object DocumentCodec {
 fun encode(d:AnimationDocument):String{val root=JSONObject();root.put("version",3);root.put("name",d.name);root.put("width",d.width);root.put("height",d.height);root.put("fps",d.fps);root.put("duration",d.duration);root.put("currentFrame",d.currentFrame);root.put("playbackStart",d.playbackStart);root.put("playbackEnd",d.playbackEnd);d.audioPath?.let{root.put("audioPath",it)};root.put("audioStartFrame",d.audioStartFrame);root.put("audioOffsetMs",d.audioOffsetMs);root.put("audioVolume",d.audioVolume.toDouble());root.put("onion",JSONObject().apply{put("enabled",d.onion.enabled);put("previous",d.onion.previousCount);put("next",d.onion.nextCount);put("opacity",d.onion.opacity);put("tintPrevious",d.onion.tintPrevious);put("tintNext",d.onion.tintNext)});root.put("camera",camera(d.camera));root.put("cameraKeys",JSONArray().apply{for(k in d.cameraKeys)put(JSONObject().apply{put("frame",k.frame);put("camera",camera(k.camera))})});val layers=JSONArray();for(layer in d.layers){val lo=JSONObject();lo.put("id",layer.id);lo.put("name",layer.name);lo.put("visible",layer.visible);lo.put("locked",layer.locked);lo.put("opacity",layer.opacity.toDouble());lo.put("blendMode",layer.blendMode);val frames=JSONArray();for((frameNo,frame) in layer.frames.toSortedMap()){val fo=JSONObject();fo.put("frame",frameNo);fo.put("id",frame.id);fo.put("exposure",frame.exposure);frame.rasterPath?.let{fo.put("rasterPath",it)};fo.put("strokes",encodeStrokes(frame.strokes));frames.put(fo)};lo.put("frames",frames);layers.put(lo)};root.put("layers",layers);return root.toString()}
 fun decode(json:String):AnimationDocument{val root=JSONObject(json);val d=AnimationDocument(name=root.optString("name","Untitled"),width=root.optInt("width",1280),height=root.optInt("height",720),fps=root.optInt("fps",24),duration=root.optInt("duration",1),currentFrame=root.optInt("currentFrame",0),playbackStart=root.optInt("playbackStart",0),playbackEnd=root.optInt("playbackEnd",0),audioPath=root.optString("audioPath","").ifEmpty{null},audioStartFrame=root.optInt("audioStartFrame",0),audioOffsetMs=root.optLong("audioOffsetMs",0),audioVolume=root.optDouble("audioVolume",1.0).toFloat());d.layers.clear();val layers=root.optJSONArray("layers")?:JSONArray();for(i in 0 until layers.length()){val lo=layers.getJSONObject(i);val layer=AnimationLayer(id=lo.optString("id",UUID.randomUUID().toString()),name=lo.optString("name","Layer"),visible=lo.optBoolean("visible",true),locked=lo.optBoolean("locked",false),opacity=lo.optDouble("opacity",1.0).toFloat(),blendMode=lo.optString("blendMode","NORMAL"));val frames=lo.optJSONArray("frames")?:JSONArray();for(j in 0 until frames.length()){val fo=frames.getJSONObject(j);val frame=DrawingFrame(id=fo.optString("id",UUID.randomUUID().toString()),exposure=fo.optInt("exposure",1),rasterPath=fo.optString("rasterPath","").ifEmpty{null});frame.strokes.addAll(decodeStrokes(fo.optJSONArray("strokes")));layer.frames[fo.optInt("frame",0)]=frame};d.layers.add(layer)};if(d.layers.isEmpty())d.layers.add(AnimationLayer(name="Layer 1"));root.optJSONObject("onion")?.let{o->d.onion.enabled=o.optBoolean("enabled",true);d.onion.previousCount=o.optInt("previous",2);d.onion.nextCount=o.optInt("next",2);d.onion.opacity=o.optInt("opacity",50);d.onion.tintPrevious=o.optBoolean("tintPrevious",true);d.onion.tintNext=o.optBoolean("tintNext",true)};copyCamera(root.optJSONObject("camera"),d.camera);val keys=root.optJSONArray("cameraKeys")?:JSONArray();for(i in 0 until keys.length()){val k=keys.getJSONObject(i);val c=AnimationCamera();copyCamera(k.optJSONObject("camera"),c);d.cameraKeys.add(CameraKeyframe(k.optInt("frame"),c))};d.normalize();return d}
 private fun camera(c:AnimationCamera)=JSONObject().apply{put("x",c.x.toDouble());put("y",c.y.toDouble());put("scale",c.scale.toDouble());put("rotation",c.rotation.toDouble())}
 private fun copyCamera(o:JSONObject?,c:AnimationCamera){if(o==null)return;c.x=o.optDouble("x").toFloat();c.y=o.optDouble("y").toFloat();c.scale=o.optDouble("scale",1.0).toFloat();c.rotation=o.optDouble("rotation").toFloat()}
 private fun encodeStrokes(list:List<StrokeData>)=JSONArray().apply{for(s in list){val o=JSONObject();o.put("id",s.id);o.put("brushId",s.brushId);o.put("color",s.color);o.put("size",s.size.toDouble());o.put("opacity",s.opacity.toDouble());o.put("settings",encodeSettings(s.brushSettings));val samples=JSONArray();for(p in s.samples)samples.put(JSONObject().apply{put("x",p.x.toDouble());put("y",p.y.toDouble());put("pressure",p.pressure.toDouble());put("timeMs",p.timeMs);put("tilt",p.tilt.toDouble());put("orientation",p.orientation.toDouble())});o.put("samples",samples);put(o)}}
 private fun decodeStrokes(a:JSONArray?):List<StrokeData>{if(a==null)return emptyList();val out=ArrayList<StrokeData>();for(i in 0 until a.length()){val o=a.getJSONObject(i);val brush=o.optString("brushId","basic");val settings=decodeSettings(o.optJSONObject("settings"),BrushDefaults.forPreset(brush));val samples=mutableListOf<StrokeSample>();val sa=o.optJSONArray("samples")?:JSONArray();for(j in 0 until sa.length()){val p=sa.getJSONObject(j);samples.add(StrokeSample(p.optDouble("x").toFloat(),p.optDouble("y").toFloat(),p.optDouble("pressure",1.0).toFloat(),p.optLong("timeMs"),p.optDouble("tilt").toFloat(),p.optDouble("orientation").toFloat()))};out.add(StrokeData(id=o.optString("id",UUID.randomUUID().toString()),brushId=brush,color=o.optInt("color",0xFF000000.toInt()),size=o.optDouble("size",settings.size.toDouble()).toFloat(),opacity=o.optDouble("opacity",settings.opacity.toDouble()).toFloat(),brushSettings=settings,samples=samples))};return out}
 private fun encodeSettings(s:BrushSettings)=JSONObject().apply{put("sizeMin",s.sizeMin.toDouble());put("sizeMax",s.sizeMax.toDouble());put("flow",s.flow.toDouble());put("alpha",s.alpha.toDouble());put("hardness",s.hardness.toDouble());put("feather",s.feather.toDouble());put("spacing",s.spacing.toDouble());put("fade",s.fade.toDouble());put("fadeIn",s.fadeIn.toDouble());put("fadeOut",s.fadeOut.toDouble());put("jitter",s.jitter.toDouble());put("pressureSize",s.pressureSize.toDouble());put("pressureOpacity",s.pressureOpacity.toDouble());put("pressureFlow",s.pressureFlow.toDouble());put("tiltSize",s.tiltSize.toDouble());put("tiltOpacity",s.tiltOpacity.toDouble());put("angle",s.angle.toDouble());put("roundness",s.roundness.toDouble());put("lockAlpha",s.lockAlpha);put("eraser",s.eraser);put("antialias",s.antialias)}
 private fun decodeSettings(o:JSONObject?,d:BrushSettings):BrushSettings{if(o==null)return d;return d.copy(sizeMin=o.optDouble("sizeMin",d.sizeMin.toDouble()).toFloat(),sizeMax=o.optDouble("sizeMax",d.sizeMax.toDouble()).toFloat(),flow=o.optDouble("flow",d.flow.toDouble()).toFloat(),alpha=o.optDouble("alpha",d.alpha.toDouble()).toFloat(),hardness=o.optDouble("hardness",d.hardness.toDouble()).toFloat(),feather=o.optDouble("feather",d.feather.toDouble()).toFloat(),spacing=o.optDouble("spacing",d.spacing.toDouble()).toFloat(),fade=o.optDouble("fade",d.fade.toDouble()).toFloat(),fadeIn=o.optDouble("fadeIn",d.fadeIn.toDouble()).toFloat(),fadeOut=o.optDouble("fadeOut",d.fadeOut.toDouble()).toFloat(),jitter=o.optDouble("jitter",d.jitter.toDouble()).toFloat(),pressureSize=o.optDouble("pressureSize",d.pressureSize.toDouble()).toFloat(),pressureOpacity=o.optDouble("pressureOpacity",d.pressureOpacity.toDouble()).toFloat(),pressureFlow=o.optDouble("pressureFlow",d.pressureFlow.toDouble()).toFloat(),tiltSize=o.optDouble("tiltSize",d.tiltSize.toDouble()).toFloat(),tiltOpacity=o.optDouble("tiltOpacity",d.tiltOpacity.toDouble()).toFloat(),angle=o.optDouble("angle",d.angle.toDouble()).toFloat(),roundness=o.optDouble("roundness",d.roundness.toDouble()).toFloat(),lockAlpha=o.optBoolean("lockAlpha",d.lockAlpha),eraser=o.optBoolean("eraser",d.eraser),antialias=o.optBoolean("antialias",d.antialias)).normalized()}
}
