package com.animame.editor

import org.json.JSONArray
import org.json.JSONObject

object DocumentCodec {
 fun encode(d:AnimationDocument):String{val r=JSONObject();r.put("version",3);r.put("name",d.name);r.put("width",d.width);r.put("height",d.height);r.put("fps",d.fps);r.put("duration",d.duration);r.put("currentFrame",d.currentFrame);r.put("playbackStart",d.playbackStart);r.put("playbackEnd",d.playbackEnd);r.put("audioPath",d.audioPath);r.put("audioStartFrame",d.audioStartFrame);r.put("audioOffsetMs",d.audioOffsetMs);r.put("audioVolume",d.audioVolume);r.put("onion",JSONObject().apply{put("enabled",d.onion.enabled);put("previous",d.onion.previousCount);put("next",d.onion.nextCount);put("opacity",d.onion.opacity);put("tintPrevious",d.onion.tintPrevious);put("tintNext",d.onion.tintNext)});r.put("camera",camera(d.camera));r.put("cameraKeys",JSONArray().apply{d.cameraKeys.forEach{put(JSONObject().apply{put("frame",it.frame);put("camera",camera(it.camera))})}});r.put("layers",JSONArray().apply{d.layers.forEach{l->put(JSONObject().apply{put("id",l.id);put("name",l.name);put("visible",l.visible);put("locked",l.locked);put("opacity",l.opacity);put("blendMode",l.blendMode);put("frames",JSONArray().apply{l.frames.entries.sortedBy{it.key}.forEach{(n,f)->put(JSONObject().apply{put("frame",n);put("id",f.id);put("exposure",f.exposure);put("rasterPath",f.rasterPath);put("strokes",strokes(f.strokes))})}})})}});return r.toString()}
 fun decode(json:String):AnimationDocument{val r=JSONObject(json);val d=AnimationDocument(name=r.optString("name","Untitled"),width=r.optInt("width",1280),height=r.optInt("height",720),fps=r.optInt("fps",24),duration=r.optInt("duration",1),currentFrame=r.optInt("currentFrame",0),playbackStart=r.optInt("playbackStart",0),playbackEnd=r.optInt("playbackEnd",0),audioPath=r.optString("audioPath","").ifEmpty{null},audioStartFrame=r.optInt("audioStartFrame",0),audioOffsetMs=r.optLong("audioOffsetMs",0L),audioVolume=r.optDouble("audioVolume",1.0).toFloat());d.layers.clear();val ls=r.optJSONArray("layers")?:JSONArray();for(i in 0 until ls.length()){val o=ls.getJSONObject(i);val l=AnimationLayer(id=o.optString("id",java.util.UUID.randomUUID().toString()),name=o.optString("name","Layer"),visible=o.optBoolean("visible",true),locked=o.optBoolean("locked",false),opacity=o.optDouble("opacity",1.0).toFloat(),blendMode=o.optString("blendMode","NORMAL"));val fs=o.optJSONArray("frames")?:JSONArray();for(j in 0 until fs.length()){val f=fs.getJSONObject(j);val df=DrawingFrame(id=f.optString("id",java.util.UUID.randomUUID().toString()),exposure=f.optInt("exposure",1),rasterPath=f.optString("rasterPath","").ifEmpty{null});df.strokes+=decodeStrokes(f.optJSONArray("strokes"));l.frames[f.optInt("frame",0)]=df};d.layers+=l};if(d.layers.isEmpty())d.layers+=AnimationLayer(name="Layer 1");r.optJSONObject("onion")?.let{o->d.onion.enabled=o.optBoolean("enabled",true);d.onion.previousCount=o.optInt("previous",2);d.onion.nextCount=o.optInt("next",2);d.onion.opacity=o.optInt("opacity",50);d.onion.tintPrevious=o.optBoolean("tintPrevious",true);d.onion.tintNext=o.optBoolean("tintNext",true)};copyCamera(r.optJSONObject("camera"),d.camera);val keys=r.optJSONArray("cameraKeys")?:JSONArray();for(i in 0 until keys.length()){val k=keys.getJSONObject(i);val c=AnimationCamera();copyCamera(k.optJSONObject("camera"),c);d.cameraKeys+=CameraKeyframe(k.optInt("frame"),c)};d.normalize();return d}
 private fun camera(c:AnimationCamera)=JSONObject().apply{put("x",c.x);put("y",c.y);put("scale",c.scale);put("rotation",c.rotation)}
 private fun copyCamera(o:JSONObject?,c:AnimationCamera){if(o==null)return;c.x=o.optDouble("x",0.0).toFloat();c.y=o.optDouble("y",0.0).toFloat();c.scale=o.optDouble("scale",1.0).toFloat();c.rotation=o.optDouble("rotation",0.0).toFloat()}
 private fun strokes(list:List<StrokeData>)=JSONArray().apply{list.forEach{s->put(JSONObject().apply{put("id",s.id);put("brushId",s.brushId);put("color",s.color);put("size",s.size);put("opacity",s.opacity);put("settings",settings(s.brushSettings));put("samples",JSONArray().apply{s.samples.forEach{p->put(JSONObject().apply{put("x",p.x);put("y",p.y);put("pressure",p.pressure);put("timeMs",p.timeMs);put("tilt",p.tilt);put("orientation",p.orientation)})}})})}}
 private fun decodeStrokes(a:JSONArray?):List<StrokeData>{if(a==null)return emptyList();val out=ArrayList<StrokeData>(a.length());for(i in 0 until a.length()){val o=a.getJSONObject(i);val brush=o.optString("brushId","basic");val ps=o.optJSONArray("samples")?:JSONArray();val sm=mutableListOf<StrokeSample>();for(j in 0 until ps.length()){val p=ps.getJSONObject(j);sm+=StrokeSample(p.optDouble("x").toFloat(),p.optDouble("y").toFloat(),p.optDouble("pressure",1.0).toFloat(),p.optLong("timeMs",0),p.optDouble("tilt",0.0).toFloat(),p.optDouble("orientation",0.0).toFloat())};val bs=decodeSettings(o.optJSONObject("settings"),BrushDefaults.forPreset(brush));out+=StrokeData(id=o.optString("id").ifEmpty{java.util.UUID.randomUUID().toString()},brushId=brush,color=o.optInt("color",0xFF000000.toInt()),size=o.optDouble("size",bs.size).toFloat(),opacity=o.optDouble("opacity",bs.opacity).toFloat(),brushSettings=bs,samples=sm)};return out}
 private fun settings(s:BrushSettings)=JSONObject().apply{put("sizeMin",s.sizeMin);put("sizeMax",s.sizeMax);put("flow",s.flow);put("alpha",s.alpha);put("hardness",s.hardness);put("feather",s.feather);put("spacing",s.spacing);put("fade",s.fade);put("fadeIn",s.fadeIn);put("fadeOut",s.fadeOut);put("jitter",s.jitter);put("pressureSize",s.pressureSize);put("pressureOpacity",s.pressureOpacity);put("pressureFlow",s.pressureFlow);put("tiltSize",s.tiltSize);put("tiltOpacity",s.tiltOpacity);put("angle",s.angle);put("roundness",s.roundness);put("lockAlpha",s.lockAlpha);put("eraser",s.eraser);put("antialias",s.antialias)}
 private fun decodeSettings(o:JSONObject?,d:BrushSettings):BrushSettings{if(o==null)return d;return d.copy(sizeMin=o.optDouble("sizeMin",d.sizeMin).toFloat(),sizeMax=o.optDouble("sizeMax",d.sizeMax).toFloat(),flow=o.optDouble("flow",d.flow).toFloat(),alpha=o.optDouble("alpha",d.alpha).toFloat(),hardness=o.optDouble("hardness",d.hardness).toFloat(),feather=o.optDouble("feather",d.feather).toFloat(),spacing=o.optDouble("spacing",d.spacing).toFloat(),fade=o.optDouble("fade",d.fade).toFloat(),fadeIn=o.optDouble("fadeIn",d.fadeIn).toFloat(),fadeOut=o.optDouble("fadeOut",d.fadeOut).toFloat(),jitter=o.optDouble("jitter",d.jitter).toFloat(),pressureSize=o.optDouble("pressureSize",d.pressureSize).toFloat(),pressureOpacity=o.optDouble("pressureOpacity",d.pressureOpacity).toFloat(),pressureFlow=o.optDouble("pressureFlow",d.pressureFlow).toFloat(),tiltSize=o.optDouble("tiltSize",d.tiltSize).toFloat(),tiltOpacity=o.optDouble("tiltOpacity",d.tiltOpacity).toFloat(),angle=o.optDouble("angle",d.angle).toFloat(),roundness=o.optDouble("roundness",d.roundness).toFloat(),lockAlpha=o.optBoolean("lockAlpha",d.lockAlpha),eraser=o.optBoolean("eraser",d.eraser),antialias=o.optBoolean("antialias",d.antialias)).normalized()}
}
