package com.animame.editor

import org.json.JSONArray
import org.json.JSONObject

object DocumentCodec {
    fun encode(document:AnimationDocument):String{val root=JSONObject();root.put("version",2);root.put("name",document.name);root.put("width",document.width);root.put("height",document.height);root.put("fps",document.fps);root.put("duration",document.duration);root.put("currentFrame",document.currentFrame);root.put("playbackStart",document.playbackStart);root.put("playbackEnd",document.playbackEnd);root.put("onion",JSONObject().apply{put("enabled",document.onion.enabled);put("previous",document.onion.previousCount);put("next",document.onion.nextCount);put("opacity",document.onion.opacity);put("tintPrevious",document.onion.tintPrevious);put("tintNext",document.onion.tintNext)});root.put("camera",camera(document.camera));root.put("cameraKeys",JSONArray().apply{document.cameraKeys.forEach{put(JSONObject().apply{put("frame",it.frame);put("camera",camera(it.camera))})}});root.put("layers",JSONArray().apply{document.layers.forEach{layer->put(JSONObject().apply{put("id",layer.id);put("name",layer.name);put("visible",layer.visible);put("locked",layer.locked);put("opacity",layer.opacity);put("blendMode",layer.blendMode);put("frames",JSONArray().apply{layer.frames.entries.sortedBy{it.key}.forEach{(n,f)->put(JSONObject().apply{put("frame",n);put("id",f.id);put("exposure",f.exposure);put("rasterPath",f.rasterPath);put("strokes",strokes(f.strokes))})}})})}});return root.toString()}
    fun decode(json:String):AnimationDocument{val root=JSONObject(json);val d=AnimationDocument(name=root.optString("name","Untitled"),width=root.optInt("width",1280),height=root.optInt("height",720),fps=root.optInt("fps",24),duration=root.optInt("duration",1),currentFrame=root.optInt("currentFrame",0),playbackStart=root.optInt("playbackStart",0),playbackEnd=root.optInt("playbackEnd",0));d.layers.clear();val ls=root.optJSONArray("layers")?:JSONArray();for(i in 0 until ls.length()){val o=ls.getJSONObject(i);val l=AnimationLayer(id=o.optString("id",java.util.UUID.randomUUID().toString()),name=o.optString("name","Layer"),visible=o.optBoolean("visible",true),locked=o.optBoolean("locked",false),opacity=o.optDouble("opacity",1.0).toFloat(),blendMode=o.optString("blendMode","NORMAL"));val fs=o.optJSONArray("frames")?:JSONArray();for(j in 0 until fs.length()){val f=fs.getJSONObject(j);val df=DrawingFrame(id=f.optString("id",java.util.UUID.randomUUID().toString()),exposure=f.optInt("exposure",1),rasterPath=f.optString("rasterPath","").ifEmpty{null});df.strokes+=decodeStrokes(f.optJSONArray("strokes"));l.frames[f.optInt("frame",0)]=df};d.layers+=l};if(d.layers.isEmpty())d.layers+=AnimationLayer(name="Layer 1");root.optJSONObject("onion")?.let{o->d.onion.enabled=o.optBoolean("enabled",true);d.onion.previousCount=o.optInt("previous",2);d.onion.nextCount=o.optInt("next",2);d.onion.opacity=o.optInt("opacity",50);d.onion.tintPrevious=o.optBoolean("tintPrevious",true);d.onion.tintNext=o.optBoolean("tintNext",true)};copyCamera(root.optJSONObject("camera"),d.camera);val keys=root.optJSONArray("cameraKeys")?:JSONArray();for(i in 0 until keys.length()){val k=keys.getJSONObject(i);val c=AnimationCamera();copyCamera(k.optJSONObject("camera"),c);d.cameraKeys+=CameraKeyframe(k.optInt("frame"),c)};d.normalize();return d}
    private fun camera(c:AnimationCamera)=JSONObject().apply{put("x",c.x);put("y",c.y);put("scale",c.scale);put("rotation",c.rotation)}
    private fun copyCamera(o:JSONObject?,c:AnimationCamera){if(o==null)return;c.x=o.optDouble("x",0.0).toFloat();c.y=o.optDouble("y",0.0).toFloat();c.scale=o.optDouble("scale",1.0).toFloat();c.rotation=o.optDouble("rotation",0.0).toFloat()}
    private fun strokes(list:List<StrokeData>)=JSONArray().apply{list.forEach{s->put(JSONObject().apply{put("id",s.id);put("brushId",s.brushId);put("color",s.color);put("size",s.size);put("opacity",s.opacity);put("settings",settings(s.brushSettings));put("samples",JSONArray().apply{s.samples.forEach{p->put(JSONObject().apply{put("x",p.x);put("y",p.y);put("pressure",p.pressure);put("timeMs",p.timeMs);put("tilt",p.tilt);put("orientation",p.orientation)})}})})}}
    private fun decodeStrokes(a:JSONArray?):List<StrokeData>{if(a==null)return emptyList();val out=ArrayList<StrokeData>(a.length());for(i in 0 until a.length()){val o=a.getJSONObject(i);val brush=o.optString("brushId","basic");val ps=o.optJSONArray("samples")?:JSONArray();val samples=mutableListOf<StrokeSample>();for(j in 0 until ps.length()){val p=ps.getJSONObject(j);samples+=StrokeSample(p.optDouble("x").toFloat(),p.optDouble("y").toFloat(),p.optDouble("pressure",1.0).toFloat(),p.optLong("timeMs",0),p.optDouble("tilt",0.0).toFloat(),p.optDouble("orientation",0.0).toFloat())};val bs=decodeSettings(o.optJSONObject("settings"),BrushDefaults.forPreset(brush));out+=StrokeData(id=o.optString("id").ifEmpty{java.util.UUID.randomUUID().toString()},brushId=brush,color=o.optInt("color",0xFF000000.toInt()),size=o.optDouble("size",bs.size).toFloat(),opacity=o.optDouble("opacity",bs.opacity).toFloat(),brushSettings=bs,samples=samples)};return out}
    private fun settings(s:BrushSettings)=JSONObject().apply{put("sizeMin",s.sizeMin);put("sizeMax",s.sizeMax);put("flow",s.flow);put("alpha",s.alpha);put("hardness",s.hardness);put("feather",s.feather);put("spacing",s.spacing);put("fade",s.fade);put("fadeIn",s.fadeIn);put("fadeOut",s.fadeOut);put("jitter",s.jitter);put("pressureSize",s.pressureSize);put("pressureOpacity",s.pressureOpacity);put("pressureFlow",s.pressureFlow);put("tiltSize",s.tiltSize);put("tiltOpacity",s.tiltOpacity);put("angle",s.angle);put("roundness",s.roundness);put("lockAlpha",s.lockAlpha);put("eraser",s.eraser);put("antialias",s.antialias)}
    private fun decodeSettings(o:JSONObject?,d:BrushSettings):BrushSettings{if(o==null)return d;return d.copy(sizeMin=o.optDouble("sizeMin",d.sizeMin).toFloat(),sizeMax=o.optDouble("sizeMax",d.sizeMax).toFloat(),flow=o.optDouble("flow",d.flow).toFloat(),alpha=o.optDouble("alpha",d.alpha).toFloat(),hardness=o.optDouble("hardness",d.hardness).toFloat(),feather=o.optDouble("feather",d.feather).toFloat(),spacing=o.optDouble("spacing",d.spacing).toFloat(),fade=o.optDouble("fade",d.fade).toFloat(),fadeIn=o.optDouble("fadeIn",d.fadeIn).toFloat(),fadeOut=o.optDouble("fadeOut",d.fadeOut).toFloat(),jitter=o.optDouble("jitter",d.jitter).toFloat(),pressureSize=o.optDouble("pressureSize",d.pressureSize).toFloat(),pressureOpacity=o.optDouble("pressureOpacity",d.pressureOpacity).toFloat(),pressureFlow=o.optDouble("pressureFlow",d.pressureFlow).toFloat(),tiltSize=o.optDouble("tiltSize",d.tiltSize).toFloat(),tiltOpacity=o.optDouble("tiltOpacity",d.tiltOpacity).toFloat(),angle=o.optDouble("angle",d.angle).toFloat(),roundness=o.optDouble("roundness",d.roundness).toFloat(),lockAlpha=o.optBoolean("lockAlpha",d.lockAlpha),eraser=o.optBoolean("eraser",d.eraser),antialias=o.optBoolean("antialias",d.antialias)).normalized()}
}
