package com.animame.editor

import android.app.Activity
import android.content.pm.ActivityInfo
import android.graphics.Color
import android.os.Bundle
import android.provider.MediaStore
import android.view.Gravity
import android.widget.*
import androidx.activity.result.contract.ActivityResultContracts
import kotlin.math.roundToInt

class MainActivity:Activity(){
 private lateinit var canvas:BrushCanvasView;private lateinit var label:TextView;private var current=BrushCatalog.presets.first()
 private val pick=registerForActivityResult(ActivityResultContracts.GetContent()){uri->uri?:return@registerForActivityResult;try{val bmp=MediaStore.Images.Media.getBitmap(contentResolver,uri);val data=BrushQrCodec.readQr(bmp);val s=data?.let{BrushQrCodec.decode(it)};if(s!=null){current=BrushCatalog.Preset("imported.${System.currentTimeMillis()}",s.name,s);canvas.settings=s;label.text="${s.name} • ${s.category}";Toast.makeText(this,"Pincel importado",Toast.LENGTH_SHORT).show()}else Toast.makeText(this,"QR não reconhecido",Toast.LENGTH_LONG).show()}catch(t:Throwable){Toast.makeText(this,"Falha no QR: ${t.message}",Toast.LENGTH_LONG).show()}}
 private val save=registerForActivityResult(ActivityResultContracts.CreateDocument("image/png")){uri->uri?:return@registerForActivityResult;try{contentResolver.openOutputStream(uri)?.use{BrushQrCodec.qrBitmap(BrushQrCodec.encode(canvas.settings)).compress(android.graphics.Bitmap.CompressFormat.PNG,100,it)};Toast.makeText(this,"QR exportado",Toast.LENGTH_SHORT).show()}catch(t:Throwable){Toast.makeText(this,"Falha ao exportar: ${t.message}",Toast.LENGTH_LONG).show()}}
 override fun onCreate(b:Bundle?){super.onCreate(b);requestedOrientation=ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE;build()}
 private fun build(){val root=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setBackgroundColor(Color.rgb(28,30,34))};val top=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;gravity=Gravity.CENTER_VERTICAL;setPadding(8,4,8,4)};label=TextView(this).apply{text="${current.name} • ${current.settings.category}";setTextColor(Color.WHITE);textSize=14f};top.addView(label,LinearLayout.LayoutParams(0,58,1f));fun btn(t:String,f:()->Unit)=Button(this).apply{text=t;setOnClickListener{f()}};top.addView(btn("Brushes"){choose()});top.addView(btn("QR Import"){pick.launch("image/*")});top.addView(btn("QR Export"){save.launch("anima-me-brush.png")});top.addView(btn("Clear"){canvas.clear()});root.addView(top);val body=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL};canvas=BrushCanvasView(this);body.addView(canvas,LinearLayout.LayoutParams(0,LinearLayout.LayoutParams.MATCH_PARENT,1f));val panel=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(8,8,8,8)};panel.addView(TextView(this).apply{text="Size";setTextColor(Color.LTGRAY)});val sz=SeekBar(this).apply{max=500;progress=current.settings.size.roundToInt();setOnSeekBarChangeListener(object:SeekBar.OnSeekBarChangeListener{override fun onProgressChanged(s:SeekBar?,v:Int,f:Boolean){canvas.size=v.coerceAtLeast(1).toFloat()};override fun onStartTrackingTouch(s:SeekBar?){};override fun onStopTrackingTouch(s:SeekBar?){} })};panel.addView(sz);panel.addView(TextView(this).apply{text="Opacity";setTextColor(Color.LTGRAY)});val op=SeekBar(this).apply{max=100;progress=92;setOnSeekBarChangeListener(object:SeekBar.OnSeekBarChangeListener{override fun onProgressChanged(s:SeekBar?,v:Int,f:Boolean){canvas.opacity=v/100f};override fun onStartTrackingTouch(s:SeekBar?){};override fun onStopTrackingTouch(s:SeekBar?){} })};panel.addView(op);body.addView(panel,LinearLayout.LayoutParams(300,LinearLayout.LayoutParams.MATCH_PARENT));root.addView(body,LinearLayout.LayoutParams.MATCH_PARENT,0).also{body.layoutParams=LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT,0,1f)};setContentView(root)}
 private fun choose(){val names=BrushCatalog.presets.map{it.name}.toTypedArray();AlertDialog.Builder(this).setTitle("Anima-me • ${names.size} pincéis").setItems(names){_,i->current=BrushCatalog.presets[i];canvas.settings=current.settings;canvas.size=current.settings.size;canvas.opacity=current.settings.opacity;label.text="${current.name} • ${current.settings.category}"}.setNegativeButton("Fechar",null).show()}
}
